version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "all"
    groups:
      gomod:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: "/examples"
    schedule:
      interval: monthly
      day: sunday
    allow:
      - dependency-type: "all"
    groups:
      gomod:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: sunday
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/tools"
    schedule:
      interval: weekly
      day: sunday
    groups:
      npm:
        patterns:
          - "*"
