with-expecter: true
disable-version-string: true
dir: mockadmin
outpkg: mockadmin
filename: "{{ .InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"

packages:
  github.com/mongodb/atlas-sdk-go/admin:
    config:
      include-regex: ".*Api"
