#!/usr/bin/env bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

for FILE in ${STAGED_GO_FILES}
do
    goimports -w "${FILE}"
    git add "${FILE}"
done

if [[ -n "${STAGED_GO_FILES}" ]]; then
    set -o errexit
    go test -race ./...
    make lint-fix
    set +o errexit
fi
