generatorName: go
gitRepoId: atlas-sdk-go
gitUserId: mongodb
vanityURL: go.mongodb.org/atlas-sdk
templateDir: "./config/go-templates"
generateInterfaces: true
enumClassPrefix: true
structPrefix: true
useOneOfDiscriminatorLookup: true
files:
  atlas_client.mustache:
    templateType: SupportingFiles
    destinationFilename: atlas_client.go
  doc.mustache:
    templateType: SupportingFiles
    destinationFilename: doc.go
