// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "go.mongodb.org/atlas-sdk/v20250312023/admin"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AlertsAPI is an autogenerated mock type for the AlertsAPI type
type AlertsAPI struct {
	mock.Mock
}

type AlertsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AlertsAPI) EXPECT() *AlertsAPI_Expecter {
	return &AlertsAPI_Expecter{mock: &_m.Mock}
}

// AcknowledgeAlert provides a mock function with given fields: ctx, groupId, alertId, acknowledgeAlert
func (_m *AlertsAPI) AcknowledgeAlert(ctx context.Context, groupId string, alertId string, acknowledgeAlert *admin.AcknowledgeAlert) admin.AcknowledgeAlertApiRequest {
	ret := _m.Called(ctx, groupId, alertId, acknowledgeAlert)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeAlert")
	}

	var r0 admin.AcknowledgeAlertApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.AcknowledgeAlert) admin.AcknowledgeAlertApiRequest); ok {
		r0 = rf(ctx, groupId, alertId, acknowledgeAlert)
	} else {
		r0 = ret.Get(0).(admin.AcknowledgeAlertApiRequest)
	}

	return r0
}

// AlertsAPI_AcknowledgeAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeAlert'
type AlertsAPI_AcknowledgeAlert_Call struct {
	*mock.Call
}

// AcknowledgeAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - alertId string
//   - acknowledgeAlert *admin.AcknowledgeAlert
func (_e *AlertsAPI_Expecter) AcknowledgeAlert(ctx any, groupId any, alertId any, acknowledgeAlert any) *AlertsAPI_AcknowledgeAlert_Call {
	return &AlertsAPI_AcknowledgeAlert_Call{Call: _e.mock.On("AcknowledgeAlert", ctx, groupId, alertId, acknowledgeAlert)}
}

func (_c *AlertsAPI_AcknowledgeAlert_Call) Run(run func(ctx context.Context, groupId string, alertId string, acknowledgeAlert *admin.AcknowledgeAlert)) *AlertsAPI_AcknowledgeAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.AcknowledgeAlert))
	})
	return _c
}

func (_c *AlertsAPI_AcknowledgeAlert_Call) Return(_a0 admin.AcknowledgeAlertApiRequest) *AlertsAPI_AcknowledgeAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_AcknowledgeAlert_Call) RunAndReturn(run func(context.Context, string, string, *admin.AcknowledgeAlert) admin.AcknowledgeAlertApiRequest) *AlertsAPI_AcknowledgeAlert_Call {
	_c.Call.Return(run)
	return _c
}

// AcknowledgeAlertExecute provides a mock function with given fields: r
func (_m *AlertsAPI) AcknowledgeAlertExecute(r admin.AcknowledgeAlertApiRequest) (*admin.AlertViewForNdsGroup, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeAlertExecute")
	}

	var r0 *admin.AlertViewForNdsGroup
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.AcknowledgeAlertApiRequest) (*admin.AlertViewForNdsGroup, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.AcknowledgeAlertApiRequest) *admin.AlertViewForNdsGroup); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.AlertViewForNdsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.AcknowledgeAlertApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.AcknowledgeAlertApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AlertsAPI_AcknowledgeAlertExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeAlertExecute'
type AlertsAPI_AcknowledgeAlertExecute_Call struct {
	*mock.Call
}

// AcknowledgeAlertExecute is a helper method to define mock.On call
//   - r admin.AcknowledgeAlertApiRequest
func (_e *AlertsAPI_Expecter) AcknowledgeAlertExecute(r any) *AlertsAPI_AcknowledgeAlertExecute_Call {
	return &AlertsAPI_AcknowledgeAlertExecute_Call{Call: _e.mock.On("AcknowledgeAlertExecute", r)}
}

func (_c *AlertsAPI_AcknowledgeAlertExecute_Call) Run(run func(r admin.AcknowledgeAlertApiRequest)) *AlertsAPI_AcknowledgeAlertExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.AcknowledgeAlertApiRequest))
	})
	return _c
}

func (_c *AlertsAPI_AcknowledgeAlertExecute_Call) Return(_a0 *admin.AlertViewForNdsGroup, _a1 *http.Response, _a2 error) *AlertsAPI_AcknowledgeAlertExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AlertsAPI_AcknowledgeAlertExecute_Call) RunAndReturn(run func(admin.AcknowledgeAlertApiRequest) (*admin.AlertViewForNdsGroup, *http.Response, error)) *AlertsAPI_AcknowledgeAlertExecute_Call {
	_c.Call.Return(run)
	return _c
}

// AcknowledgeAlertWithParams provides a mock function with given fields: ctx, args
func (_m *AlertsAPI) AcknowledgeAlertWithParams(ctx context.Context, args *admin.AcknowledgeAlertApiParams) admin.AcknowledgeAlertApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeAlertWithParams")
	}

	var r0 admin.AcknowledgeAlertApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.AcknowledgeAlertApiParams) admin.AcknowledgeAlertApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.AcknowledgeAlertApiRequest)
	}

	return r0
}

// AlertsAPI_AcknowledgeAlertWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeAlertWithParams'
type AlertsAPI_AcknowledgeAlertWithParams_Call struct {
	*mock.Call
}

// AcknowledgeAlertWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.AcknowledgeAlertApiParams
func (_e *AlertsAPI_Expecter) AcknowledgeAlertWithParams(ctx any, args any) *AlertsAPI_AcknowledgeAlertWithParams_Call {
	return &AlertsAPI_AcknowledgeAlertWithParams_Call{Call: _e.mock.On("AcknowledgeAlertWithParams", ctx, args)}
}

func (_c *AlertsAPI_AcknowledgeAlertWithParams_Call) Run(run func(ctx context.Context, args *admin.AcknowledgeAlertApiParams)) *AlertsAPI_AcknowledgeAlertWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.AcknowledgeAlertApiParams))
	})
	return _c
}

func (_c *AlertsAPI_AcknowledgeAlertWithParams_Call) Return(_a0 admin.AcknowledgeAlertApiRequest) *AlertsAPI_AcknowledgeAlertWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_AcknowledgeAlertWithParams_Call) RunAndReturn(run func(context.Context, *admin.AcknowledgeAlertApiParams) admin.AcknowledgeAlertApiRequest) *AlertsAPI_AcknowledgeAlertWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlert provides a mock function with given fields: ctx, groupId, alertId
func (_m *AlertsAPI) GetAlert(ctx context.Context, groupId string, alertId string) admin.GetAlertApiRequest {
	ret := _m.Called(ctx, groupId, alertId)

	if len(ret) == 0 {
		panic("no return value specified for GetAlert")
	}

	var r0 admin.GetAlertApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetAlertApiRequest); ok {
		r0 = rf(ctx, groupId, alertId)
	} else {
		r0 = ret.Get(0).(admin.GetAlertApiRequest)
	}

	return r0
}

// AlertsAPI_GetAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlert'
type AlertsAPI_GetAlert_Call struct {
	*mock.Call
}

// GetAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - alertId string
func (_e *AlertsAPI_Expecter) GetAlert(ctx any, groupId any, alertId any) *AlertsAPI_GetAlert_Call {
	return &AlertsAPI_GetAlert_Call{Call: _e.mock.On("GetAlert", ctx, groupId, alertId)}
}

func (_c *AlertsAPI_GetAlert_Call) Run(run func(ctx context.Context, groupId string, alertId string)) *AlertsAPI_GetAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AlertsAPI_GetAlert_Call) Return(_a0 admin.GetAlertApiRequest) *AlertsAPI_GetAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_GetAlert_Call) RunAndReturn(run func(context.Context, string, string) admin.GetAlertApiRequest) *AlertsAPI_GetAlert_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlertConfigAlerts provides a mock function with given fields: ctx, groupId, alertConfigId
func (_m *AlertsAPI) GetAlertConfigAlerts(ctx context.Context, groupId string, alertConfigId string) admin.GetAlertConfigAlertsApiRequest {
	ret := _m.Called(ctx, groupId, alertConfigId)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertConfigAlerts")
	}

	var r0 admin.GetAlertConfigAlertsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetAlertConfigAlertsApiRequest); ok {
		r0 = rf(ctx, groupId, alertConfigId)
	} else {
		r0 = ret.Get(0).(admin.GetAlertConfigAlertsApiRequest)
	}

	return r0
}

// AlertsAPI_GetAlertConfigAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlertConfigAlerts'
type AlertsAPI_GetAlertConfigAlerts_Call struct {
	*mock.Call
}

// GetAlertConfigAlerts is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - alertConfigId string
func (_e *AlertsAPI_Expecter) GetAlertConfigAlerts(ctx any, groupId any, alertConfigId any) *AlertsAPI_GetAlertConfigAlerts_Call {
	return &AlertsAPI_GetAlertConfigAlerts_Call{Call: _e.mock.On("GetAlertConfigAlerts", ctx, groupId, alertConfigId)}
}

func (_c *AlertsAPI_GetAlertConfigAlerts_Call) Run(run func(ctx context.Context, groupId string, alertConfigId string)) *AlertsAPI_GetAlertConfigAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AlertsAPI_GetAlertConfigAlerts_Call) Return(_a0 admin.GetAlertConfigAlertsApiRequest) *AlertsAPI_GetAlertConfigAlerts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_GetAlertConfigAlerts_Call) RunAndReturn(run func(context.Context, string, string) admin.GetAlertConfigAlertsApiRequest) *AlertsAPI_GetAlertConfigAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlertConfigAlertsExecute provides a mock function with given fields: r
func (_m *AlertsAPI) GetAlertConfigAlertsExecute(r admin.GetAlertConfigAlertsApiRequest) (*admin.PaginatedAlert, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertConfigAlertsExecute")
	}

	var r0 *admin.PaginatedAlert
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetAlertConfigAlertsApiRequest) (*admin.PaginatedAlert, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetAlertConfigAlertsApiRequest) *admin.PaginatedAlert); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetAlertConfigAlertsApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetAlertConfigAlertsApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AlertsAPI_GetAlertConfigAlertsExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlertConfigAlertsExecute'
type AlertsAPI_GetAlertConfigAlertsExecute_Call struct {
	*mock.Call
}

// GetAlertConfigAlertsExecute is a helper method to define mock.On call
//   - r admin.GetAlertConfigAlertsApiRequest
func (_e *AlertsAPI_Expecter) GetAlertConfigAlertsExecute(r any) *AlertsAPI_GetAlertConfigAlertsExecute_Call {
	return &AlertsAPI_GetAlertConfigAlertsExecute_Call{Call: _e.mock.On("GetAlertConfigAlertsExecute", r)}
}

func (_c *AlertsAPI_GetAlertConfigAlertsExecute_Call) Run(run func(r admin.GetAlertConfigAlertsApiRequest)) *AlertsAPI_GetAlertConfigAlertsExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetAlertConfigAlertsApiRequest))
	})
	return _c
}

func (_c *AlertsAPI_GetAlertConfigAlertsExecute_Call) Return(_a0 *admin.PaginatedAlert, _a1 *http.Response, _a2 error) *AlertsAPI_GetAlertConfigAlertsExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AlertsAPI_GetAlertConfigAlertsExecute_Call) RunAndReturn(run func(admin.GetAlertConfigAlertsApiRequest) (*admin.PaginatedAlert, *http.Response, error)) *AlertsAPI_GetAlertConfigAlertsExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlertConfigAlertsWithParams provides a mock function with given fields: ctx, args
func (_m *AlertsAPI) GetAlertConfigAlertsWithParams(ctx context.Context, args *admin.GetAlertConfigAlertsApiParams) admin.GetAlertConfigAlertsApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertConfigAlertsWithParams")
	}

	var r0 admin.GetAlertConfigAlertsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetAlertConfigAlertsApiParams) admin.GetAlertConfigAlertsApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetAlertConfigAlertsApiRequest)
	}

	return r0
}

// AlertsAPI_GetAlertConfigAlertsWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlertConfigAlertsWithParams'
type AlertsAPI_GetAlertConfigAlertsWithParams_Call struct {
	*mock.Call
}

// GetAlertConfigAlertsWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetAlertConfigAlertsApiParams
func (_e *AlertsAPI_Expecter) GetAlertConfigAlertsWithParams(ctx any, args any) *AlertsAPI_GetAlertConfigAlertsWithParams_Call {
	return &AlertsAPI_GetAlertConfigAlertsWithParams_Call{Call: _e.mock.On("GetAlertConfigAlertsWithParams", ctx, args)}
}

func (_c *AlertsAPI_GetAlertConfigAlertsWithParams_Call) Run(run func(ctx context.Context, args *admin.GetAlertConfigAlertsApiParams)) *AlertsAPI_GetAlertConfigAlertsWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetAlertConfigAlertsApiParams))
	})
	return _c
}

func (_c *AlertsAPI_GetAlertConfigAlertsWithParams_Call) Return(_a0 admin.GetAlertConfigAlertsApiRequest) *AlertsAPI_GetAlertConfigAlertsWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_GetAlertConfigAlertsWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetAlertConfigAlertsApiParams) admin.GetAlertConfigAlertsApiRequest) *AlertsAPI_GetAlertConfigAlertsWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlertExecute provides a mock function with given fields: r
func (_m *AlertsAPI) GetAlertExecute(r admin.GetAlertApiRequest) (*admin.AlertViewForNdsGroup, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertExecute")
	}

	var r0 *admin.AlertViewForNdsGroup
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetAlertApiRequest) (*admin.AlertViewForNdsGroup, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetAlertApiRequest) *admin.AlertViewForNdsGroup); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.AlertViewForNdsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetAlertApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetAlertApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AlertsAPI_GetAlertExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlertExecute'
type AlertsAPI_GetAlertExecute_Call struct {
	*mock.Call
}

// GetAlertExecute is a helper method to define mock.On call
//   - r admin.GetAlertApiRequest
func (_e *AlertsAPI_Expecter) GetAlertExecute(r any) *AlertsAPI_GetAlertExecute_Call {
	return &AlertsAPI_GetAlertExecute_Call{Call: _e.mock.On("GetAlertExecute", r)}
}

func (_c *AlertsAPI_GetAlertExecute_Call) Run(run func(r admin.GetAlertApiRequest)) *AlertsAPI_GetAlertExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetAlertApiRequest))
	})
	return _c
}

func (_c *AlertsAPI_GetAlertExecute_Call) Return(_a0 *admin.AlertViewForNdsGroup, _a1 *http.Response, _a2 error) *AlertsAPI_GetAlertExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AlertsAPI_GetAlertExecute_Call) RunAndReturn(run func(admin.GetAlertApiRequest) (*admin.AlertViewForNdsGroup, *http.Response, error)) *AlertsAPI_GetAlertExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlertWithParams provides a mock function with given fields: ctx, args
func (_m *AlertsAPI) GetAlertWithParams(ctx context.Context, args *admin.GetAlertApiParams) admin.GetAlertApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertWithParams")
	}

	var r0 admin.GetAlertApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetAlertApiParams) admin.GetAlertApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetAlertApiRequest)
	}

	return r0
}

// AlertsAPI_GetAlertWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlertWithParams'
type AlertsAPI_GetAlertWithParams_Call struct {
	*mock.Call
}

// GetAlertWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetAlertApiParams
func (_e *AlertsAPI_Expecter) GetAlertWithParams(ctx any, args any) *AlertsAPI_GetAlertWithParams_Call {
	return &AlertsAPI_GetAlertWithParams_Call{Call: _e.mock.On("GetAlertWithParams", ctx, args)}
}

func (_c *AlertsAPI_GetAlertWithParams_Call) Run(run func(ctx context.Context, args *admin.GetAlertApiParams)) *AlertsAPI_GetAlertWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetAlertApiParams))
	})
	return _c
}

func (_c *AlertsAPI_GetAlertWithParams_Call) Return(_a0 admin.GetAlertApiRequest) *AlertsAPI_GetAlertWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_GetAlertWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetAlertApiParams) admin.GetAlertApiRequest) *AlertsAPI_GetAlertWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListAlerts provides a mock function with given fields: ctx, groupId
func (_m *AlertsAPI) ListAlerts(ctx context.Context, groupId string) admin.ListAlertsApiRequest {
	ret := _m.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for ListAlerts")
	}

	var r0 admin.ListAlertsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.ListAlertsApiRequest); ok {
		r0 = rf(ctx, groupId)
	} else {
		r0 = ret.Get(0).(admin.ListAlertsApiRequest)
	}

	return r0
}

// AlertsAPI_ListAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAlerts'
type AlertsAPI_ListAlerts_Call struct {
	*mock.Call
}

// ListAlerts is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
func (_e *AlertsAPI_Expecter) ListAlerts(ctx any, groupId any) *AlertsAPI_ListAlerts_Call {
	return &AlertsAPI_ListAlerts_Call{Call: _e.mock.On("ListAlerts", ctx, groupId)}
}

func (_c *AlertsAPI_ListAlerts_Call) Run(run func(ctx context.Context, groupId string)) *AlertsAPI_ListAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AlertsAPI_ListAlerts_Call) Return(_a0 admin.ListAlertsApiRequest) *AlertsAPI_ListAlerts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_ListAlerts_Call) RunAndReturn(run func(context.Context, string) admin.ListAlertsApiRequest) *AlertsAPI_ListAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// ListAlertsExecute provides a mock function with given fields: r
func (_m *AlertsAPI) ListAlertsExecute(r admin.ListAlertsApiRequest) (*admin.PaginatedAlert, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListAlertsExecute")
	}

	var r0 *admin.PaginatedAlert
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListAlertsApiRequest) (*admin.PaginatedAlert, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListAlertsApiRequest) *admin.PaginatedAlert); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListAlertsApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListAlertsApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AlertsAPI_ListAlertsExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAlertsExecute'
type AlertsAPI_ListAlertsExecute_Call struct {
	*mock.Call
}

// ListAlertsExecute is a helper method to define mock.On call
//   - r admin.ListAlertsApiRequest
func (_e *AlertsAPI_Expecter) ListAlertsExecute(r any) *AlertsAPI_ListAlertsExecute_Call {
	return &AlertsAPI_ListAlertsExecute_Call{Call: _e.mock.On("ListAlertsExecute", r)}
}

func (_c *AlertsAPI_ListAlertsExecute_Call) Run(run func(r admin.ListAlertsApiRequest)) *AlertsAPI_ListAlertsExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListAlertsApiRequest))
	})
	return _c
}

func (_c *AlertsAPI_ListAlertsExecute_Call) Return(_a0 *admin.PaginatedAlert, _a1 *http.Response, _a2 error) *AlertsAPI_ListAlertsExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AlertsAPI_ListAlertsExecute_Call) RunAndReturn(run func(admin.ListAlertsApiRequest) (*admin.PaginatedAlert, *http.Response, error)) *AlertsAPI_ListAlertsExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListAlertsWithParams provides a mock function with given fields: ctx, args
func (_m *AlertsAPI) ListAlertsWithParams(ctx context.Context, args *admin.ListAlertsApiParams) admin.ListAlertsApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListAlertsWithParams")
	}

	var r0 admin.ListAlertsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListAlertsApiParams) admin.ListAlertsApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListAlertsApiRequest)
	}

	return r0
}

// AlertsAPI_ListAlertsWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAlertsWithParams'
type AlertsAPI_ListAlertsWithParams_Call struct {
	*mock.Call
}

// ListAlertsWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListAlertsApiParams
func (_e *AlertsAPI_Expecter) ListAlertsWithParams(ctx any, args any) *AlertsAPI_ListAlertsWithParams_Call {
	return &AlertsAPI_ListAlertsWithParams_Call{Call: _e.mock.On("ListAlertsWithParams", ctx, args)}
}

func (_c *AlertsAPI_ListAlertsWithParams_Call) Run(run func(ctx context.Context, args *admin.ListAlertsApiParams)) *AlertsAPI_ListAlertsWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListAlertsApiParams))
	})
	return _c
}

func (_c *AlertsAPI_ListAlertsWithParams_Call) Return(_a0 admin.ListAlertsApiRequest) *AlertsAPI_ListAlertsWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertsAPI_ListAlertsWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListAlertsApiParams) admin.ListAlertsApiRequest) *AlertsAPI_ListAlertsWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlertsAPI creates a new instance of AlertsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertsAPI {
	mock := &AlertsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
