// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "go.mongodb.org/atlas-sdk/v20250312023/admin"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ProgrammaticAPIKeysAPI is an autogenerated mock type for the ProgrammaticAPIKeysAPI type
type ProgrammaticAPIKeysAPI struct {
	mock.Mock
}

type ProgrammaticAPIKeysAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *ProgrammaticAPIKeysAPI) EXPECT() *ProgrammaticAPIKeysAPI_Expecter {
	return &ProgrammaticAPIKeysAPI_Expecter{mock: &_m.Mock}
}

// AddGroupApiKey provides a mock function with given fields: ctx, groupId, apiUserId, userAccessRoleAssignment
func (_m *ProgrammaticAPIKeysAPI) AddGroupApiKey(ctx context.Context, groupId string, apiUserId string, userAccessRoleAssignment *[]admin.UserAccessRoleAssignment) admin.AddGroupApiKeyApiRequest {
	ret := _m.Called(ctx, groupId, apiUserId, userAccessRoleAssignment)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupApiKey")
	}

	var r0 admin.AddGroupApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *[]admin.UserAccessRoleAssignment) admin.AddGroupApiKeyApiRequest); ok {
		r0 = rf(ctx, groupId, apiUserId, userAccessRoleAssignment)
	} else {
		r0 = ret.Get(0).(admin.AddGroupApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_AddGroupApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupApiKey'
type ProgrammaticAPIKeysAPI_AddGroupApiKey_Call struct {
	*mock.Call
}

// AddGroupApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - apiUserId string
//   - userAccessRoleAssignment *[]admin.UserAccessRoleAssignment
func (_e *ProgrammaticAPIKeysAPI_Expecter) AddGroupApiKey(ctx any, groupId any, apiUserId any, userAccessRoleAssignment any) *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call {
	return &ProgrammaticAPIKeysAPI_AddGroupApiKey_Call{Call: _e.mock.On("AddGroupApiKey", ctx, groupId, apiUserId, userAccessRoleAssignment)}
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call) Run(run func(ctx context.Context, groupId string, apiUserId string, userAccessRoleAssignment *[]admin.UserAccessRoleAssignment)) *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*[]admin.UserAccessRoleAssignment))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call) Return(_a0 admin.AddGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call) RunAndReturn(run func(context.Context, string, string, *[]admin.UserAccessRoleAssignment) admin.AddGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_AddGroupApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// AddGroupApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) AddGroupApiKeyExecute(r admin.AddGroupApiKeyApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupApiKeyExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.AddGroupApiKeyApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.AddGroupApiKeyApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.AddGroupApiKeyApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupApiKeyExecute'
type ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call struct {
	*mock.Call
}

// AddGroupApiKeyExecute is a helper method to define mock.On call
//   - r admin.AddGroupApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) AddGroupApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call{Call: _e.mock.On("AddGroupApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call) Run(run func(r admin.AddGroupApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.AddGroupApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call) Return(_a0 *http.Response, _a1 error) *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call) RunAndReturn(run func(admin.AddGroupApiKeyApiRequest) (*http.Response, error)) *ProgrammaticAPIKeysAPI_AddGroupApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// AddGroupApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) AddGroupApiKeyWithParams(ctx context.Context, args *admin.AddGroupApiKeyApiParams) admin.AddGroupApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupApiKeyWithParams")
	}

	var r0 admin.AddGroupApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.AddGroupApiKeyApiParams) admin.AddGroupApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.AddGroupApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupApiKeyWithParams'
type ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call struct {
	*mock.Call
}

// AddGroupApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.AddGroupApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) AddGroupApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call{Call: _e.mock.On("AddGroupApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.AddGroupApiKeyApiParams)) *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.AddGroupApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call) Return(_a0 admin.AddGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.AddGroupApiKeyApiParams) admin.AddGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_AddGroupApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupApiKey provides a mock function with given fields: ctx, groupId, createAtlasProjectApiKey
func (_m *ProgrammaticAPIKeysAPI) CreateGroupApiKey(ctx context.Context, groupId string, createAtlasProjectApiKey *admin.CreateAtlasProjectApiKey) admin.CreateGroupApiKeyApiRequest {
	ret := _m.Called(ctx, groupId, createAtlasProjectApiKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupApiKey")
	}

	var r0 admin.CreateGroupApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, *admin.CreateAtlasProjectApiKey) admin.CreateGroupApiKeyApiRequest); ok {
		r0 = rf(ctx, groupId, createAtlasProjectApiKey)
	} else {
		r0 = ret.Get(0).(admin.CreateGroupApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupApiKey'
type ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call struct {
	*mock.Call
}

// CreateGroupApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - createAtlasProjectApiKey *admin.CreateAtlasProjectApiKey
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateGroupApiKey(ctx any, groupId any, createAtlasProjectApiKey any) *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call {
	return &ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call{Call: _e.mock.On("CreateGroupApiKey", ctx, groupId, createAtlasProjectApiKey)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call) Run(run func(ctx context.Context, groupId string, createAtlasProjectApiKey *admin.CreateAtlasProjectApiKey)) *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*admin.CreateAtlasProjectApiKey))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call) Return(_a0 admin.CreateGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call) RunAndReturn(run func(context.Context, string, *admin.CreateAtlasProjectApiKey) admin.CreateGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateGroupApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) CreateGroupApiKeyExecute(r admin.CreateGroupApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupApiKeyExecute")
	}

	var r0 *admin.ApiKeyUserDetails
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateGroupApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateGroupApiKeyApiRequest) *admin.ApiKeyUserDetails); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ApiKeyUserDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateGroupApiKeyApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateGroupApiKeyApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupApiKeyExecute'
type ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call struct {
	*mock.Call
}

// CreateGroupApiKeyExecute is a helper method to define mock.On call
//   - r admin.CreateGroupApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateGroupApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call{Call: _e.mock.On("CreateGroupApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call) Run(run func(r admin.CreateGroupApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateGroupApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call) Return(_a0 *admin.ApiKeyUserDetails, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call) RunAndReturn(run func(admin.CreateGroupApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) CreateGroupApiKeyWithParams(ctx context.Context, args *admin.CreateGroupApiKeyApiParams) admin.CreateGroupApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupApiKeyWithParams")
	}

	var r0 admin.CreateGroupApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateGroupApiKeyApiParams) admin.CreateGroupApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateGroupApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupApiKeyWithParams'
type ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call struct {
	*mock.Call
}

// CreateGroupApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateGroupApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateGroupApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call{Call: _e.mock.On("CreateGroupApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateGroupApiKeyApiParams)) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateGroupApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call) Return(_a0 admin.CreateGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateGroupApiKeyApiParams) admin.CreateGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateGroupApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgAccessEntry provides a mock function with given fields: ctx, orgId, apiUserId, userAccessListRequest
func (_m *ProgrammaticAPIKeysAPI) CreateOrgAccessEntry(ctx context.Context, orgId string, apiUserId string, userAccessListRequest *[]admin.UserAccessListRequest) admin.CreateOrgAccessEntryApiRequest {
	ret := _m.Called(ctx, orgId, apiUserId, userAccessListRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgAccessEntry")
	}

	var r0 admin.CreateOrgAccessEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *[]admin.UserAccessListRequest) admin.CreateOrgAccessEntryApiRequest); ok {
		r0 = rf(ctx, orgId, apiUserId, userAccessListRequest)
	} else {
		r0 = ret.Get(0).(admin.CreateOrgAccessEntryApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgAccessEntry'
type ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call struct {
	*mock.Call
}

// CreateOrgAccessEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - apiUserId string
//   - userAccessListRequest *[]admin.UserAccessListRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateOrgAccessEntry(ctx any, orgId any, apiUserId any, userAccessListRequest any) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call {
	return &ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call{Call: _e.mock.On("CreateOrgAccessEntry", ctx, orgId, apiUserId, userAccessListRequest)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call) Run(run func(ctx context.Context, orgId string, apiUserId string, userAccessListRequest *[]admin.UserAccessListRequest)) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*[]admin.UserAccessListRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call) Return(_a0 admin.CreateOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call) RunAndReturn(run func(context.Context, string, string, *[]admin.UserAccessListRequest) admin.CreateOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgAccessEntryExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) CreateOrgAccessEntryExecute(r admin.CreateOrgAccessEntryApiRequest) (*admin.PaginatedApiUserAccessListResponse, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgAccessEntryExecute")
	}

	var r0 *admin.PaginatedApiUserAccessListResponse
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateOrgAccessEntryApiRequest) (*admin.PaginatedApiUserAccessListResponse, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateOrgAccessEntryApiRequest) *admin.PaginatedApiUserAccessListResponse); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedApiUserAccessListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateOrgAccessEntryApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateOrgAccessEntryApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgAccessEntryExecute'
type ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call struct {
	*mock.Call
}

// CreateOrgAccessEntryExecute is a helper method to define mock.On call
//   - r admin.CreateOrgAccessEntryApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateOrgAccessEntryExecute(r any) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call {
	return &ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call{Call: _e.mock.On("CreateOrgAccessEntryExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call) Run(run func(r admin.CreateOrgAccessEntryApiRequest)) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateOrgAccessEntryApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call) Return(_a0 *admin.PaginatedApiUserAccessListResponse, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call) RunAndReturn(run func(admin.CreateOrgAccessEntryApiRequest) (*admin.PaginatedApiUserAccessListResponse, *http.Response, error)) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgAccessEntryWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) CreateOrgAccessEntryWithParams(ctx context.Context, args *admin.CreateOrgAccessEntryApiParams) admin.CreateOrgAccessEntryApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgAccessEntryWithParams")
	}

	var r0 admin.CreateOrgAccessEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateOrgAccessEntryApiParams) admin.CreateOrgAccessEntryApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateOrgAccessEntryApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgAccessEntryWithParams'
type ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call struct {
	*mock.Call
}

// CreateOrgAccessEntryWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateOrgAccessEntryApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateOrgAccessEntryWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call {
	return &ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call{Call: _e.mock.On("CreateOrgAccessEntryWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateOrgAccessEntryApiParams)) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateOrgAccessEntryApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call) Return(_a0 admin.CreateOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateOrgAccessEntryApiParams) admin.CreateOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgAccessEntryWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgApiKey provides a mock function with given fields: ctx, orgId, createAtlasOrganizationApiKey
func (_m *ProgrammaticAPIKeysAPI) CreateOrgApiKey(ctx context.Context, orgId string, createAtlasOrganizationApiKey *admin.CreateAtlasOrganizationApiKey) admin.CreateOrgApiKeyApiRequest {
	ret := _m.Called(ctx, orgId, createAtlasOrganizationApiKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgApiKey")
	}

	var r0 admin.CreateOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, *admin.CreateAtlasOrganizationApiKey) admin.CreateOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, orgId, createAtlasOrganizationApiKey)
	} else {
		r0 = ret.Get(0).(admin.CreateOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgApiKey'
type ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call struct {
	*mock.Call
}

// CreateOrgApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - createAtlasOrganizationApiKey *admin.CreateAtlasOrganizationApiKey
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateOrgApiKey(ctx any, orgId any, createAtlasOrganizationApiKey any) *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call {
	return &ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call{Call: _e.mock.On("CreateOrgApiKey", ctx, orgId, createAtlasOrganizationApiKey)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call) Run(run func(ctx context.Context, orgId string, createAtlasOrganizationApiKey *admin.CreateAtlasOrganizationApiKey)) *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*admin.CreateAtlasOrganizationApiKey))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call) Return(_a0 admin.CreateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call) RunAndReturn(run func(context.Context, string, *admin.CreateAtlasOrganizationApiKey) admin.CreateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) CreateOrgApiKeyExecute(r admin.CreateOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgApiKeyExecute")
	}

	var r0 *admin.ApiKeyUserDetails
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateOrgApiKeyApiRequest) *admin.ApiKeyUserDetails); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ApiKeyUserDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateOrgApiKeyApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateOrgApiKeyApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgApiKeyExecute'
type ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call struct {
	*mock.Call
}

// CreateOrgApiKeyExecute is a helper method to define mock.On call
//   - r admin.CreateOrgApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateOrgApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call{Call: _e.mock.On("CreateOrgApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call) Run(run func(r admin.CreateOrgApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateOrgApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call) Return(_a0 *admin.ApiKeyUserDetails, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call) RunAndReturn(run func(admin.CreateOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) CreateOrgApiKeyWithParams(ctx context.Context, args *admin.CreateOrgApiKeyApiParams) admin.CreateOrgApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgApiKeyWithParams")
	}

	var r0 admin.CreateOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateOrgApiKeyApiParams) admin.CreateOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgApiKeyWithParams'
type ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call struct {
	*mock.Call
}

// CreateOrgApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateOrgApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) CreateOrgApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call{Call: _e.mock.On("CreateOrgApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateOrgApiKeyApiParams)) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateOrgApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call) Return(_a0 admin.CreateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateOrgApiKeyApiParams) admin.CreateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_CreateOrgApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessEntry provides a mock function with given fields: ctx, orgId, apiUserId, ipAddress
func (_m *ProgrammaticAPIKeysAPI) DeleteAccessEntry(ctx context.Context, orgId string, apiUserId string, ipAddress string) admin.DeleteAccessEntryApiRequest {
	ret := _m.Called(ctx, orgId, apiUserId, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessEntry")
	}

	var r0 admin.DeleteAccessEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) admin.DeleteAccessEntryApiRequest); ok {
		r0 = rf(ctx, orgId, apiUserId, ipAddress)
	} else {
		r0 = ret.Get(0).(admin.DeleteAccessEntryApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessEntry'
type ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call struct {
	*mock.Call
}

// DeleteAccessEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - apiUserId string
//   - ipAddress string
func (_e *ProgrammaticAPIKeysAPI_Expecter) DeleteAccessEntry(ctx any, orgId any, apiUserId any, ipAddress any) *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call {
	return &ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call{Call: _e.mock.On("DeleteAccessEntry", ctx, orgId, apiUserId, ipAddress)}
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call) Run(run func(ctx context.Context, orgId string, apiUserId string, ipAddress string)) *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call) Return(_a0 admin.DeleteAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call) RunAndReturn(run func(context.Context, string, string, string) admin.DeleteAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_DeleteAccessEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessEntryExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) DeleteAccessEntryExecute(r admin.DeleteAccessEntryApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessEntryExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.DeleteAccessEntryApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DeleteAccessEntryApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DeleteAccessEntryApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessEntryExecute'
type ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call struct {
	*mock.Call
}

// DeleteAccessEntryExecute is a helper method to define mock.On call
//   - r admin.DeleteAccessEntryApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) DeleteAccessEntryExecute(r any) *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call {
	return &ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call{Call: _e.mock.On("DeleteAccessEntryExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call) Run(run func(r admin.DeleteAccessEntryApiRequest)) *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DeleteAccessEntryApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call) Return(_a0 *http.Response, _a1 error) *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call) RunAndReturn(run func(admin.DeleteAccessEntryApiRequest) (*http.Response, error)) *ProgrammaticAPIKeysAPI_DeleteAccessEntryExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessEntryWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) DeleteAccessEntryWithParams(ctx context.Context, args *admin.DeleteAccessEntryApiParams) admin.DeleteAccessEntryApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessEntryWithParams")
	}

	var r0 admin.DeleteAccessEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteAccessEntryApiParams) admin.DeleteAccessEntryApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DeleteAccessEntryApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessEntryWithParams'
type ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call struct {
	*mock.Call
}

// DeleteAccessEntryWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DeleteAccessEntryApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) DeleteAccessEntryWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call {
	return &ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call{Call: _e.mock.On("DeleteAccessEntryWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call) Run(run func(ctx context.Context, args *admin.DeleteAccessEntryApiParams)) *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DeleteAccessEntryApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call) Return(_a0 admin.DeleteAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call) RunAndReturn(run func(context.Context, *admin.DeleteAccessEntryApiParams) admin.DeleteAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_DeleteAccessEntryWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgApiKey provides a mock function with given fields: ctx, orgId, apiUserId
func (_m *ProgrammaticAPIKeysAPI) DeleteOrgApiKey(ctx context.Context, orgId string, apiUserId string) admin.DeleteOrgApiKeyApiRequest {
	ret := _m.Called(ctx, orgId, apiUserId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgApiKey")
	}

	var r0 admin.DeleteOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.DeleteOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, orgId, apiUserId)
	} else {
		r0 = ret.Get(0).(admin.DeleteOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgApiKey'
type ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call struct {
	*mock.Call
}

// DeleteOrgApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - apiUserId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) DeleteOrgApiKey(ctx any, orgId any, apiUserId any) *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call {
	return &ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call{Call: _e.mock.On("DeleteOrgApiKey", ctx, orgId, apiUserId)}
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call) Run(run func(ctx context.Context, orgId string, apiUserId string)) *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call) Return(_a0 admin.DeleteOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call) RunAndReturn(run func(context.Context, string, string) admin.DeleteOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_DeleteOrgApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) DeleteOrgApiKeyExecute(r admin.DeleteOrgApiKeyApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgApiKeyExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.DeleteOrgApiKeyApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DeleteOrgApiKeyApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DeleteOrgApiKeyApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgApiKeyExecute'
type ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call struct {
	*mock.Call
}

// DeleteOrgApiKeyExecute is a helper method to define mock.On call
//   - r admin.DeleteOrgApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) DeleteOrgApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call{Call: _e.mock.On("DeleteOrgApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call) Run(run func(r admin.DeleteOrgApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DeleteOrgApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call) Return(_a0 *http.Response, _a1 error) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call) RunAndReturn(run func(admin.DeleteOrgApiKeyApiRequest) (*http.Response, error)) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) DeleteOrgApiKeyWithParams(ctx context.Context, args *admin.DeleteOrgApiKeyApiParams) admin.DeleteOrgApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgApiKeyWithParams")
	}

	var r0 admin.DeleteOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteOrgApiKeyApiParams) admin.DeleteOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DeleteOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgApiKeyWithParams'
type ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call struct {
	*mock.Call
}

// DeleteOrgApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DeleteOrgApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) DeleteOrgApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call{Call: _e.mock.On("DeleteOrgApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.DeleteOrgApiKeyApiParams)) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DeleteOrgApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call) Return(_a0 admin.DeleteOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.DeleteOrgApiKeyApiParams) admin.DeleteOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_DeleteOrgApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgAccessEntry provides a mock function with given fields: ctx, orgId, ipAddress, apiUserId
func (_m *ProgrammaticAPIKeysAPI) GetOrgAccessEntry(ctx context.Context, orgId string, ipAddress string, apiUserId string) admin.GetOrgAccessEntryApiRequest {
	ret := _m.Called(ctx, orgId, ipAddress, apiUserId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgAccessEntry")
	}

	var r0 admin.GetOrgAccessEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) admin.GetOrgAccessEntryApiRequest); ok {
		r0 = rf(ctx, orgId, ipAddress, apiUserId)
	} else {
		r0 = ret.Get(0).(admin.GetOrgAccessEntryApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgAccessEntry'
type ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call struct {
	*mock.Call
}

// GetOrgAccessEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - ipAddress string
//   - apiUserId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) GetOrgAccessEntry(ctx any, orgId any, ipAddress any, apiUserId any) *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call {
	return &ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call{Call: _e.mock.On("GetOrgAccessEntry", ctx, orgId, ipAddress, apiUserId)}
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call) Run(run func(ctx context.Context, orgId string, ipAddress string, apiUserId string)) *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call) Return(_a0 admin.GetOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call) RunAndReturn(run func(context.Context, string, string, string) admin.GetOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_GetOrgAccessEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgAccessEntryExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) GetOrgAccessEntryExecute(r admin.GetOrgAccessEntryApiRequest) (*admin.UserAccessListResponse, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgAccessEntryExecute")
	}

	var r0 *admin.UserAccessListResponse
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetOrgAccessEntryApiRequest) (*admin.UserAccessListResponse, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetOrgAccessEntryApiRequest) *admin.UserAccessListResponse); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.UserAccessListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetOrgAccessEntryApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetOrgAccessEntryApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgAccessEntryExecute'
type ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call struct {
	*mock.Call
}

// GetOrgAccessEntryExecute is a helper method to define mock.On call
//   - r admin.GetOrgAccessEntryApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) GetOrgAccessEntryExecute(r any) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call {
	return &ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call{Call: _e.mock.On("GetOrgAccessEntryExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call) Run(run func(r admin.GetOrgAccessEntryApiRequest)) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetOrgAccessEntryApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call) Return(_a0 *admin.UserAccessListResponse, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call) RunAndReturn(run func(admin.GetOrgAccessEntryApiRequest) (*admin.UserAccessListResponse, *http.Response, error)) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgAccessEntryWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) GetOrgAccessEntryWithParams(ctx context.Context, args *admin.GetOrgAccessEntryApiParams) admin.GetOrgAccessEntryApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgAccessEntryWithParams")
	}

	var r0 admin.GetOrgAccessEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetOrgAccessEntryApiParams) admin.GetOrgAccessEntryApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetOrgAccessEntryApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgAccessEntryWithParams'
type ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call struct {
	*mock.Call
}

// GetOrgAccessEntryWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetOrgAccessEntryApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) GetOrgAccessEntryWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call {
	return &ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call{Call: _e.mock.On("GetOrgAccessEntryWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call) Run(run func(ctx context.Context, args *admin.GetOrgAccessEntryApiParams)) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetOrgAccessEntryApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call) Return(_a0 admin.GetOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetOrgAccessEntryApiParams) admin.GetOrgAccessEntryApiRequest) *ProgrammaticAPIKeysAPI_GetOrgAccessEntryWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgApiKey provides a mock function with given fields: ctx, orgId, apiUserId
func (_m *ProgrammaticAPIKeysAPI) GetOrgApiKey(ctx context.Context, orgId string, apiUserId string) admin.GetOrgApiKeyApiRequest {
	ret := _m.Called(ctx, orgId, apiUserId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgApiKey")
	}

	var r0 admin.GetOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, orgId, apiUserId)
	} else {
		r0 = ret.Get(0).(admin.GetOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_GetOrgApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgApiKey'
type ProgrammaticAPIKeysAPI_GetOrgApiKey_Call struct {
	*mock.Call
}

// GetOrgApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - apiUserId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) GetOrgApiKey(ctx any, orgId any, apiUserId any) *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call {
	return &ProgrammaticAPIKeysAPI_GetOrgApiKey_Call{Call: _e.mock.On("GetOrgApiKey", ctx, orgId, apiUserId)}
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call) Run(run func(ctx context.Context, orgId string, apiUserId string)) *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call) Return(_a0 admin.GetOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call) RunAndReturn(run func(context.Context, string, string) admin.GetOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_GetOrgApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) GetOrgApiKeyExecute(r admin.GetOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgApiKeyExecute")
	}

	var r0 *admin.ApiKeyUserDetails
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetOrgApiKeyApiRequest) *admin.ApiKeyUserDetails); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ApiKeyUserDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetOrgApiKeyApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetOrgApiKeyApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgApiKeyExecute'
type ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call struct {
	*mock.Call
}

// GetOrgApiKeyExecute is a helper method to define mock.On call
//   - r admin.GetOrgApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) GetOrgApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call{Call: _e.mock.On("GetOrgApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call) Run(run func(r admin.GetOrgApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetOrgApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call) Return(_a0 *admin.ApiKeyUserDetails, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call) RunAndReturn(run func(admin.GetOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)) *ProgrammaticAPIKeysAPI_GetOrgApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) GetOrgApiKeyWithParams(ctx context.Context, args *admin.GetOrgApiKeyApiParams) admin.GetOrgApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgApiKeyWithParams")
	}

	var r0 admin.GetOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetOrgApiKeyApiParams) admin.GetOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgApiKeyWithParams'
type ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call struct {
	*mock.Call
}

// GetOrgApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetOrgApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) GetOrgApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call{Call: _e.mock.On("GetOrgApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.GetOrgApiKeyApiParams)) *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetOrgApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call) Return(_a0 admin.GetOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetOrgApiKeyApiParams) admin.GetOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_GetOrgApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupApiKeys provides a mock function with given fields: ctx, groupId
func (_m *ProgrammaticAPIKeysAPI) ListGroupApiKeys(ctx context.Context, groupId string) admin.ListGroupApiKeysApiRequest {
	ret := _m.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupApiKeys")
	}

	var r0 admin.ListGroupApiKeysApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.ListGroupApiKeysApiRequest); ok {
		r0 = rf(ctx, groupId)
	} else {
		r0 = ret.Get(0).(admin.ListGroupApiKeysApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupApiKeys'
type ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call struct {
	*mock.Call
}

// ListGroupApiKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListGroupApiKeys(ctx any, groupId any) *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call {
	return &ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call{Call: _e.mock.On("ListGroupApiKeys", ctx, groupId)}
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call) Run(run func(ctx context.Context, groupId string)) *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call) Return(_a0 admin.ListGroupApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call) RunAndReturn(run func(context.Context, string) admin.ListGroupApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListGroupApiKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupApiKeysExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) ListGroupApiKeysExecute(r admin.ListGroupApiKeysApiRequest) (*admin.PaginatedApiApiUser, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupApiKeysExecute")
	}

	var r0 *admin.PaginatedApiApiUser
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListGroupApiKeysApiRequest) (*admin.PaginatedApiApiUser, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListGroupApiKeysApiRequest) *admin.PaginatedApiApiUser); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedApiApiUser)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListGroupApiKeysApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListGroupApiKeysApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupApiKeysExecute'
type ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call struct {
	*mock.Call
}

// ListGroupApiKeysExecute is a helper method to define mock.On call
//   - r admin.ListGroupApiKeysApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListGroupApiKeysExecute(r any) *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call {
	return &ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call{Call: _e.mock.On("ListGroupApiKeysExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call) Run(run func(r admin.ListGroupApiKeysApiRequest)) *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListGroupApiKeysApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call) Return(_a0 *admin.PaginatedApiApiUser, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call) RunAndReturn(run func(admin.ListGroupApiKeysApiRequest) (*admin.PaginatedApiApiUser, *http.Response, error)) *ProgrammaticAPIKeysAPI_ListGroupApiKeysExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupApiKeysWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) ListGroupApiKeysWithParams(ctx context.Context, args *admin.ListGroupApiKeysApiParams) admin.ListGroupApiKeysApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupApiKeysWithParams")
	}

	var r0 admin.ListGroupApiKeysApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListGroupApiKeysApiParams) admin.ListGroupApiKeysApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListGroupApiKeysApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupApiKeysWithParams'
type ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call struct {
	*mock.Call
}

// ListGroupApiKeysWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListGroupApiKeysApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListGroupApiKeysWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call {
	return &ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call{Call: _e.mock.On("ListGroupApiKeysWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call) Run(run func(ctx context.Context, args *admin.ListGroupApiKeysApiParams)) *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListGroupApiKeysApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call) Return(_a0 admin.ListGroupApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListGroupApiKeysApiParams) admin.ListGroupApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListGroupApiKeysWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgAccessEntries provides a mock function with given fields: ctx, orgId, apiUserId
func (_m *ProgrammaticAPIKeysAPI) ListOrgAccessEntries(ctx context.Context, orgId string, apiUserId string) admin.ListOrgAccessEntriesApiRequest {
	ret := _m.Called(ctx, orgId, apiUserId)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgAccessEntries")
	}

	var r0 admin.ListOrgAccessEntriesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.ListOrgAccessEntriesApiRequest); ok {
		r0 = rf(ctx, orgId, apiUserId)
	} else {
		r0 = ret.Get(0).(admin.ListOrgAccessEntriesApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgAccessEntries'
type ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call struct {
	*mock.Call
}

// ListOrgAccessEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - apiUserId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListOrgAccessEntries(ctx any, orgId any, apiUserId any) *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call {
	return &ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call{Call: _e.mock.On("ListOrgAccessEntries", ctx, orgId, apiUserId)}
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call) Run(run func(ctx context.Context, orgId string, apiUserId string)) *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call) Return(_a0 admin.ListOrgAccessEntriesApiRequest) *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call) RunAndReturn(run func(context.Context, string, string) admin.ListOrgAccessEntriesApiRequest) *ProgrammaticAPIKeysAPI_ListOrgAccessEntries_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgAccessEntriesExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) ListOrgAccessEntriesExecute(r admin.ListOrgAccessEntriesApiRequest) (*admin.PaginatedApiUserAccessListResponse, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgAccessEntriesExecute")
	}

	var r0 *admin.PaginatedApiUserAccessListResponse
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListOrgAccessEntriesApiRequest) (*admin.PaginatedApiUserAccessListResponse, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListOrgAccessEntriesApiRequest) *admin.PaginatedApiUserAccessListResponse); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedApiUserAccessListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListOrgAccessEntriesApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListOrgAccessEntriesApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgAccessEntriesExecute'
type ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call struct {
	*mock.Call
}

// ListOrgAccessEntriesExecute is a helper method to define mock.On call
//   - r admin.ListOrgAccessEntriesApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListOrgAccessEntriesExecute(r any) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call {
	return &ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call{Call: _e.mock.On("ListOrgAccessEntriesExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call) Run(run func(r admin.ListOrgAccessEntriesApiRequest)) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListOrgAccessEntriesApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call) Return(_a0 *admin.PaginatedApiUserAccessListResponse, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call) RunAndReturn(run func(admin.ListOrgAccessEntriesApiRequest) (*admin.PaginatedApiUserAccessListResponse, *http.Response, error)) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgAccessEntriesWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) ListOrgAccessEntriesWithParams(ctx context.Context, args *admin.ListOrgAccessEntriesApiParams) admin.ListOrgAccessEntriesApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgAccessEntriesWithParams")
	}

	var r0 admin.ListOrgAccessEntriesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListOrgAccessEntriesApiParams) admin.ListOrgAccessEntriesApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListOrgAccessEntriesApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgAccessEntriesWithParams'
type ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call struct {
	*mock.Call
}

// ListOrgAccessEntriesWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListOrgAccessEntriesApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListOrgAccessEntriesWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call {
	return &ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call{Call: _e.mock.On("ListOrgAccessEntriesWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call) Run(run func(ctx context.Context, args *admin.ListOrgAccessEntriesApiParams)) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListOrgAccessEntriesApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call) Return(_a0 admin.ListOrgAccessEntriesApiRequest) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListOrgAccessEntriesApiParams) admin.ListOrgAccessEntriesApiRequest) *ProgrammaticAPIKeysAPI_ListOrgAccessEntriesWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgApiKeys provides a mock function with given fields: ctx, orgId
func (_m *ProgrammaticAPIKeysAPI) ListOrgApiKeys(ctx context.Context, orgId string) admin.ListOrgApiKeysApiRequest {
	ret := _m.Called(ctx, orgId)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgApiKeys")
	}

	var r0 admin.ListOrgApiKeysApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.ListOrgApiKeysApiRequest); ok {
		r0 = rf(ctx, orgId)
	} else {
		r0 = ret.Get(0).(admin.ListOrgApiKeysApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgApiKeys'
type ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call struct {
	*mock.Call
}

// ListOrgApiKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListOrgApiKeys(ctx any, orgId any) *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call {
	return &ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call{Call: _e.mock.On("ListOrgApiKeys", ctx, orgId)}
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call) Run(run func(ctx context.Context, orgId string)) *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call) Return(_a0 admin.ListOrgApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call) RunAndReturn(run func(context.Context, string) admin.ListOrgApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListOrgApiKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgApiKeysExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) ListOrgApiKeysExecute(r admin.ListOrgApiKeysApiRequest) (*admin.PaginatedApiApiUser, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgApiKeysExecute")
	}

	var r0 *admin.PaginatedApiApiUser
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListOrgApiKeysApiRequest) (*admin.PaginatedApiApiUser, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListOrgApiKeysApiRequest) *admin.PaginatedApiApiUser); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedApiApiUser)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListOrgApiKeysApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListOrgApiKeysApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgApiKeysExecute'
type ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call struct {
	*mock.Call
}

// ListOrgApiKeysExecute is a helper method to define mock.On call
//   - r admin.ListOrgApiKeysApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListOrgApiKeysExecute(r any) *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call {
	return &ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call{Call: _e.mock.On("ListOrgApiKeysExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call) Run(run func(r admin.ListOrgApiKeysApiRequest)) *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListOrgApiKeysApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call) Return(_a0 *admin.PaginatedApiApiUser, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call) RunAndReturn(run func(admin.ListOrgApiKeysApiRequest) (*admin.PaginatedApiApiUser, *http.Response, error)) *ProgrammaticAPIKeysAPI_ListOrgApiKeysExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgApiKeysWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) ListOrgApiKeysWithParams(ctx context.Context, args *admin.ListOrgApiKeysApiParams) admin.ListOrgApiKeysApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgApiKeysWithParams")
	}

	var r0 admin.ListOrgApiKeysApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListOrgApiKeysApiParams) admin.ListOrgApiKeysApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListOrgApiKeysApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgApiKeysWithParams'
type ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call struct {
	*mock.Call
}

// ListOrgApiKeysWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListOrgApiKeysApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) ListOrgApiKeysWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call {
	return &ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call{Call: _e.mock.On("ListOrgApiKeysWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call) Run(run func(ctx context.Context, args *admin.ListOrgApiKeysApiParams)) *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListOrgApiKeysApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call) Return(_a0 admin.ListOrgApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListOrgApiKeysApiParams) admin.ListOrgApiKeysApiRequest) *ProgrammaticAPIKeysAPI_ListOrgApiKeysWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGroupApiKey provides a mock function with given fields: ctx, groupId, apiUserId
func (_m *ProgrammaticAPIKeysAPI) RemoveGroupApiKey(ctx context.Context, groupId string, apiUserId string) admin.RemoveGroupApiKeyApiRequest {
	ret := _m.Called(ctx, groupId, apiUserId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroupApiKey")
	}

	var r0 admin.RemoveGroupApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.RemoveGroupApiKeyApiRequest); ok {
		r0 = rf(ctx, groupId, apiUserId)
	} else {
		r0 = ret.Get(0).(admin.RemoveGroupApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGroupApiKey'
type ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call struct {
	*mock.Call
}

// RemoveGroupApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - apiUserId string
func (_e *ProgrammaticAPIKeysAPI_Expecter) RemoveGroupApiKey(ctx any, groupId any, apiUserId any) *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call {
	return &ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call{Call: _e.mock.On("RemoveGroupApiKey", ctx, groupId, apiUserId)}
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call) Run(run func(ctx context.Context, groupId string, apiUserId string)) *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call) Return(_a0 admin.RemoveGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call) RunAndReturn(run func(context.Context, string, string) admin.RemoveGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_RemoveGroupApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGroupApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) RemoveGroupApiKeyExecute(r admin.RemoveGroupApiKeyApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroupApiKeyExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.RemoveGroupApiKeyApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.RemoveGroupApiKeyApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.RemoveGroupApiKeyApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGroupApiKeyExecute'
type ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call struct {
	*mock.Call
}

// RemoveGroupApiKeyExecute is a helper method to define mock.On call
//   - r admin.RemoveGroupApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) RemoveGroupApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call{Call: _e.mock.On("RemoveGroupApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call) Run(run func(r admin.RemoveGroupApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.RemoveGroupApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call) Return(_a0 *http.Response, _a1 error) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call) RunAndReturn(run func(admin.RemoveGroupApiKeyApiRequest) (*http.Response, error)) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGroupApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) RemoveGroupApiKeyWithParams(ctx context.Context, args *admin.RemoveGroupApiKeyApiParams) admin.RemoveGroupApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroupApiKeyWithParams")
	}

	var r0 admin.RemoveGroupApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.RemoveGroupApiKeyApiParams) admin.RemoveGroupApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.RemoveGroupApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGroupApiKeyWithParams'
type ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call struct {
	*mock.Call
}

// RemoveGroupApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.RemoveGroupApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) RemoveGroupApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call{Call: _e.mock.On("RemoveGroupApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.RemoveGroupApiKeyApiParams)) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.RemoveGroupApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call) Return(_a0 admin.RemoveGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.RemoveGroupApiKeyApiParams) admin.RemoveGroupApiKeyApiRequest) *ProgrammaticAPIKeysAPI_RemoveGroupApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApiKeyRoles provides a mock function with given fields: ctx, groupId, apiUserId, updateAtlasProjectApiKey
func (_m *ProgrammaticAPIKeysAPI) UpdateApiKeyRoles(ctx context.Context, groupId string, apiUserId string, updateAtlasProjectApiKey *admin.UpdateAtlasProjectApiKey) admin.UpdateApiKeyRolesApiRequest {
	ret := _m.Called(ctx, groupId, apiUserId, updateAtlasProjectApiKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApiKeyRoles")
	}

	var r0 admin.UpdateApiKeyRolesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.UpdateAtlasProjectApiKey) admin.UpdateApiKeyRolesApiRequest); ok {
		r0 = rf(ctx, groupId, apiUserId, updateAtlasProjectApiKey)
	} else {
		r0 = ret.Get(0).(admin.UpdateApiKeyRolesApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApiKeyRoles'
type ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call struct {
	*mock.Call
}

// UpdateApiKeyRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - apiUserId string
//   - updateAtlasProjectApiKey *admin.UpdateAtlasProjectApiKey
func (_e *ProgrammaticAPIKeysAPI_Expecter) UpdateApiKeyRoles(ctx any, groupId any, apiUserId any, updateAtlasProjectApiKey any) *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call {
	return &ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call{Call: _e.mock.On("UpdateApiKeyRoles", ctx, groupId, apiUserId, updateAtlasProjectApiKey)}
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call) Run(run func(ctx context.Context, groupId string, apiUserId string, updateAtlasProjectApiKey *admin.UpdateAtlasProjectApiKey)) *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.UpdateAtlasProjectApiKey))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call) Return(_a0 admin.UpdateApiKeyRolesApiRequest) *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call) RunAndReturn(run func(context.Context, string, string, *admin.UpdateAtlasProjectApiKey) admin.UpdateApiKeyRolesApiRequest) *ProgrammaticAPIKeysAPI_UpdateApiKeyRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApiKeyRolesExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) UpdateApiKeyRolesExecute(r admin.UpdateApiKeyRolesApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApiKeyRolesExecute")
	}

	var r0 *admin.ApiKeyUserDetails
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.UpdateApiKeyRolesApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.UpdateApiKeyRolesApiRequest) *admin.ApiKeyUserDetails); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ApiKeyUserDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.UpdateApiKeyRolesApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.UpdateApiKeyRolesApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApiKeyRolesExecute'
type ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call struct {
	*mock.Call
}

// UpdateApiKeyRolesExecute is a helper method to define mock.On call
//   - r admin.UpdateApiKeyRolesApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) UpdateApiKeyRolesExecute(r any) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call {
	return &ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call{Call: _e.mock.On("UpdateApiKeyRolesExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call) Run(run func(r admin.UpdateApiKeyRolesApiRequest)) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.UpdateApiKeyRolesApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call) Return(_a0 *admin.ApiKeyUserDetails, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call) RunAndReturn(run func(admin.UpdateApiKeyRolesApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesExecute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApiKeyRolesWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) UpdateApiKeyRolesWithParams(ctx context.Context, args *admin.UpdateApiKeyRolesApiParams) admin.UpdateApiKeyRolesApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApiKeyRolesWithParams")
	}

	var r0 admin.UpdateApiKeyRolesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.UpdateApiKeyRolesApiParams) admin.UpdateApiKeyRolesApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.UpdateApiKeyRolesApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApiKeyRolesWithParams'
type ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call struct {
	*mock.Call
}

// UpdateApiKeyRolesWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.UpdateApiKeyRolesApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) UpdateApiKeyRolesWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call {
	return &ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call{Call: _e.mock.On("UpdateApiKeyRolesWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call) Run(run func(ctx context.Context, args *admin.UpdateApiKeyRolesApiParams)) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.UpdateApiKeyRolesApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call) Return(_a0 admin.UpdateApiKeyRolesApiRequest) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call) RunAndReturn(run func(context.Context, *admin.UpdateApiKeyRolesApiParams) admin.UpdateApiKeyRolesApiRequest) *ProgrammaticAPIKeysAPI_UpdateApiKeyRolesWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgApiKey provides a mock function with given fields: ctx, orgId, apiUserId, updateAtlasOrganizationApiKey
func (_m *ProgrammaticAPIKeysAPI) UpdateOrgApiKey(ctx context.Context, orgId string, apiUserId string, updateAtlasOrganizationApiKey *admin.UpdateAtlasOrganizationApiKey) admin.UpdateOrgApiKeyApiRequest {
	ret := _m.Called(ctx, orgId, apiUserId, updateAtlasOrganizationApiKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgApiKey")
	}

	var r0 admin.UpdateOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.UpdateAtlasOrganizationApiKey) admin.UpdateOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, orgId, apiUserId, updateAtlasOrganizationApiKey)
	} else {
		r0 = ret.Get(0).(admin.UpdateOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgApiKey'
type ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call struct {
	*mock.Call
}

// UpdateOrgApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - apiUserId string
//   - updateAtlasOrganizationApiKey *admin.UpdateAtlasOrganizationApiKey
func (_e *ProgrammaticAPIKeysAPI_Expecter) UpdateOrgApiKey(ctx any, orgId any, apiUserId any, updateAtlasOrganizationApiKey any) *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call {
	return &ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call{Call: _e.mock.On("UpdateOrgApiKey", ctx, orgId, apiUserId, updateAtlasOrganizationApiKey)}
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call) Run(run func(ctx context.Context, orgId string, apiUserId string, updateAtlasOrganizationApiKey *admin.UpdateAtlasOrganizationApiKey)) *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.UpdateAtlasOrganizationApiKey))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call) Return(_a0 admin.UpdateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call) RunAndReturn(run func(context.Context, string, string, *admin.UpdateAtlasOrganizationApiKey) admin.UpdateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_UpdateOrgApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgApiKeyExecute provides a mock function with given fields: r
func (_m *ProgrammaticAPIKeysAPI) UpdateOrgApiKeyExecute(r admin.UpdateOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgApiKeyExecute")
	}

	var r0 *admin.ApiKeyUserDetails
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.UpdateOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.UpdateOrgApiKeyApiRequest) *admin.ApiKeyUserDetails); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ApiKeyUserDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.UpdateOrgApiKeyApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.UpdateOrgApiKeyApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgApiKeyExecute'
type ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call struct {
	*mock.Call
}

// UpdateOrgApiKeyExecute is a helper method to define mock.On call
//   - r admin.UpdateOrgApiKeyApiRequest
func (_e *ProgrammaticAPIKeysAPI_Expecter) UpdateOrgApiKeyExecute(r any) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call {
	return &ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call{Call: _e.mock.On("UpdateOrgApiKeyExecute", r)}
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call) Run(run func(r admin.UpdateOrgApiKeyApiRequest)) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.UpdateOrgApiKeyApiRequest))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call) Return(_a0 *admin.ApiKeyUserDetails, _a1 *http.Response, _a2 error) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call) RunAndReturn(run func(admin.UpdateOrgApiKeyApiRequest) (*admin.ApiKeyUserDetails, *http.Response, error)) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyExecute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgApiKeyWithParams provides a mock function with given fields: ctx, args
func (_m *ProgrammaticAPIKeysAPI) UpdateOrgApiKeyWithParams(ctx context.Context, args *admin.UpdateOrgApiKeyApiParams) admin.UpdateOrgApiKeyApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgApiKeyWithParams")
	}

	var r0 admin.UpdateOrgApiKeyApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.UpdateOrgApiKeyApiParams) admin.UpdateOrgApiKeyApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.UpdateOrgApiKeyApiRequest)
	}

	return r0
}

// ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgApiKeyWithParams'
type ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call struct {
	*mock.Call
}

// UpdateOrgApiKeyWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.UpdateOrgApiKeyApiParams
func (_e *ProgrammaticAPIKeysAPI_Expecter) UpdateOrgApiKeyWithParams(ctx any, args any) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call {
	return &ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call{Call: _e.mock.On("UpdateOrgApiKeyWithParams", ctx, args)}
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call) Run(run func(ctx context.Context, args *admin.UpdateOrgApiKeyApiParams)) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.UpdateOrgApiKeyApiParams))
	})
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call) Return(_a0 admin.UpdateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call) RunAndReturn(run func(context.Context, *admin.UpdateOrgApiKeyApiParams) admin.UpdateOrgApiKeyApiRequest) *ProgrammaticAPIKeysAPI_UpdateOrgApiKeyWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewProgrammaticAPIKeysAPI creates a new instance of ProgrammaticAPIKeysAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProgrammaticAPIKeysAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProgrammaticAPIKeysAPI {
	mock := &ProgrammaticAPIKeysAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
