// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "go.mongodb.org/atlas-sdk/v20250312022/admin"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ProjectIPAccessListAPI is an autogenerated mock type for the ProjectIPAccessListAPI type
type ProjectIPAccessListAPI struct {
	mock.Mock
}

type ProjectIPAccessListAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectIPAccessListAPI) EXPECT() *ProjectIPAccessListAPI_Expecter {
	return &ProjectIPAccessListAPI_Expecter{mock: &_m.Mock}
}

// CreateAccessListEntry provides a mock function with given fields: ctx, groupId, networkPermissionEntry
func (_m *ProjectIPAccessListAPI) CreateAccessListEntry(ctx context.Context, groupId string, networkPermissionEntry *[]admin.NetworkPermissionEntry) admin.CreateAccessListEntryApiRequest {
	ret := _m.Called(ctx, groupId, networkPermissionEntry)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessListEntry")
	}

	var r0 admin.CreateAccessListEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, *[]admin.NetworkPermissionEntry) admin.CreateAccessListEntryApiRequest); ok {
		r0 = rf(ctx, groupId, networkPermissionEntry)
	} else {
		r0 = ret.Get(0).(admin.CreateAccessListEntryApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_CreateAccessListEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessListEntry'
type ProjectIPAccessListAPI_CreateAccessListEntry_Call struct {
	*mock.Call
}

// CreateAccessListEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - networkPermissionEntry *[]admin.NetworkPermissionEntry
func (_e *ProjectIPAccessListAPI_Expecter) CreateAccessListEntry(ctx any, groupId any, networkPermissionEntry any) *ProjectIPAccessListAPI_CreateAccessListEntry_Call {
	return &ProjectIPAccessListAPI_CreateAccessListEntry_Call{Call: _e.mock.On("CreateAccessListEntry", ctx, groupId, networkPermissionEntry)}
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntry_Call) Run(run func(ctx context.Context, groupId string, networkPermissionEntry *[]admin.NetworkPermissionEntry)) *ProjectIPAccessListAPI_CreateAccessListEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*[]admin.NetworkPermissionEntry))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntry_Call) Return(_a0 admin.CreateAccessListEntryApiRequest) *ProjectIPAccessListAPI_CreateAccessListEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntry_Call) RunAndReturn(run func(context.Context, string, *[]admin.NetworkPermissionEntry) admin.CreateAccessListEntryApiRequest) *ProjectIPAccessListAPI_CreateAccessListEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccessListEntryExecute provides a mock function with given fields: r
func (_m *ProjectIPAccessListAPI) CreateAccessListEntryExecute(r admin.CreateAccessListEntryApiRequest) (*admin.PaginatedNetworkAccess, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessListEntryExecute")
	}

	var r0 *admin.PaginatedNetworkAccess
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateAccessListEntryApiRequest) (*admin.PaginatedNetworkAccess, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateAccessListEntryApiRequest) *admin.PaginatedNetworkAccess); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedNetworkAccess)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateAccessListEntryApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateAccessListEntryApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessListEntryExecute'
type ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call struct {
	*mock.Call
}

// CreateAccessListEntryExecute is a helper method to define mock.On call
//   - r admin.CreateAccessListEntryApiRequest
func (_e *ProjectIPAccessListAPI_Expecter) CreateAccessListEntryExecute(r any) *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call {
	return &ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call{Call: _e.mock.On("CreateAccessListEntryExecute", r)}
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call) Run(run func(r admin.CreateAccessListEntryApiRequest)) *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateAccessListEntryApiRequest))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call) Return(_a0 *admin.PaginatedNetworkAccess, _a1 *http.Response, _a2 error) *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call) RunAndReturn(run func(admin.CreateAccessListEntryApiRequest) (*admin.PaginatedNetworkAccess, *http.Response, error)) *ProjectIPAccessListAPI_CreateAccessListEntryExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccessListEntryWithParams provides a mock function with given fields: ctx, args
func (_m *ProjectIPAccessListAPI) CreateAccessListEntryWithParams(ctx context.Context, args *admin.CreateAccessListEntryApiParams) admin.CreateAccessListEntryApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessListEntryWithParams")
	}

	var r0 admin.CreateAccessListEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateAccessListEntryApiParams) admin.CreateAccessListEntryApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateAccessListEntryApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessListEntryWithParams'
type ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call struct {
	*mock.Call
}

// CreateAccessListEntryWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateAccessListEntryApiParams
func (_e *ProjectIPAccessListAPI_Expecter) CreateAccessListEntryWithParams(ctx any, args any) *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call {
	return &ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call{Call: _e.mock.On("CreateAccessListEntryWithParams", ctx, args)}
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateAccessListEntryApiParams)) *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateAccessListEntryApiParams))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call) Return(_a0 admin.CreateAccessListEntryApiRequest) *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateAccessListEntryApiParams) admin.CreateAccessListEntryApiRequest) *ProjectIPAccessListAPI_CreateAccessListEntryWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessListEntry provides a mock function with given fields: ctx, groupId, entryValue
func (_m *ProjectIPAccessListAPI) DeleteAccessListEntry(ctx context.Context, groupId string, entryValue string) admin.DeleteAccessListEntryApiRequest {
	ret := _m.Called(ctx, groupId, entryValue)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessListEntry")
	}

	var r0 admin.DeleteAccessListEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.DeleteAccessListEntryApiRequest); ok {
		r0 = rf(ctx, groupId, entryValue)
	} else {
		r0 = ret.Get(0).(admin.DeleteAccessListEntryApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_DeleteAccessListEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessListEntry'
type ProjectIPAccessListAPI_DeleteAccessListEntry_Call struct {
	*mock.Call
}

// DeleteAccessListEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - entryValue string
func (_e *ProjectIPAccessListAPI_Expecter) DeleteAccessListEntry(ctx any, groupId any, entryValue any) *ProjectIPAccessListAPI_DeleteAccessListEntry_Call {
	return &ProjectIPAccessListAPI_DeleteAccessListEntry_Call{Call: _e.mock.On("DeleteAccessListEntry", ctx, groupId, entryValue)}
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntry_Call) Run(run func(ctx context.Context, groupId string, entryValue string)) *ProjectIPAccessListAPI_DeleteAccessListEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntry_Call) Return(_a0 admin.DeleteAccessListEntryApiRequest) *ProjectIPAccessListAPI_DeleteAccessListEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntry_Call) RunAndReturn(run func(context.Context, string, string) admin.DeleteAccessListEntryApiRequest) *ProjectIPAccessListAPI_DeleteAccessListEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessListEntryExecute provides a mock function with given fields: r
func (_m *ProjectIPAccessListAPI) DeleteAccessListEntryExecute(r admin.DeleteAccessListEntryApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessListEntryExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.DeleteAccessListEntryApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DeleteAccessListEntryApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DeleteAccessListEntryApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessListEntryExecute'
type ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call struct {
	*mock.Call
}

// DeleteAccessListEntryExecute is a helper method to define mock.On call
//   - r admin.DeleteAccessListEntryApiRequest
func (_e *ProjectIPAccessListAPI_Expecter) DeleteAccessListEntryExecute(r any) *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call {
	return &ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call{Call: _e.mock.On("DeleteAccessListEntryExecute", r)}
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call) Run(run func(r admin.DeleteAccessListEntryApiRequest)) *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DeleteAccessListEntryApiRequest))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call) Return(_a0 *http.Response, _a1 error) *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call) RunAndReturn(run func(admin.DeleteAccessListEntryApiRequest) (*http.Response, error)) *ProjectIPAccessListAPI_DeleteAccessListEntryExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessListEntryWithParams provides a mock function with given fields: ctx, args
func (_m *ProjectIPAccessListAPI) DeleteAccessListEntryWithParams(ctx context.Context, args *admin.DeleteAccessListEntryApiParams) admin.DeleteAccessListEntryApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessListEntryWithParams")
	}

	var r0 admin.DeleteAccessListEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteAccessListEntryApiParams) admin.DeleteAccessListEntryApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DeleteAccessListEntryApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessListEntryWithParams'
type ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call struct {
	*mock.Call
}

// DeleteAccessListEntryWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DeleteAccessListEntryApiParams
func (_e *ProjectIPAccessListAPI_Expecter) DeleteAccessListEntryWithParams(ctx any, args any) *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call {
	return &ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call{Call: _e.mock.On("DeleteAccessListEntryWithParams", ctx, args)}
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call) Run(run func(ctx context.Context, args *admin.DeleteAccessListEntryApiParams)) *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DeleteAccessListEntryApiParams))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call) Return(_a0 admin.DeleteAccessListEntryApiRequest) *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call) RunAndReturn(run func(context.Context, *admin.DeleteAccessListEntryApiParams) admin.DeleteAccessListEntryApiRequest) *ProjectIPAccessListAPI_DeleteAccessListEntryWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessListEntry provides a mock function with given fields: ctx, groupId, entryValue
func (_m *ProjectIPAccessListAPI) GetAccessListEntry(ctx context.Context, groupId string, entryValue string) admin.GetAccessListEntryApiRequest {
	ret := _m.Called(ctx, groupId, entryValue)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessListEntry")
	}

	var r0 admin.GetAccessListEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetAccessListEntryApiRequest); ok {
		r0 = rf(ctx, groupId, entryValue)
	} else {
		r0 = ret.Get(0).(admin.GetAccessListEntryApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_GetAccessListEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessListEntry'
type ProjectIPAccessListAPI_GetAccessListEntry_Call struct {
	*mock.Call
}

// GetAccessListEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - entryValue string
func (_e *ProjectIPAccessListAPI_Expecter) GetAccessListEntry(ctx any, groupId any, entryValue any) *ProjectIPAccessListAPI_GetAccessListEntry_Call {
	return &ProjectIPAccessListAPI_GetAccessListEntry_Call{Call: _e.mock.On("GetAccessListEntry", ctx, groupId, entryValue)}
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntry_Call) Run(run func(ctx context.Context, groupId string, entryValue string)) *ProjectIPAccessListAPI_GetAccessListEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntry_Call) Return(_a0 admin.GetAccessListEntryApiRequest) *ProjectIPAccessListAPI_GetAccessListEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntry_Call) RunAndReturn(run func(context.Context, string, string) admin.GetAccessListEntryApiRequest) *ProjectIPAccessListAPI_GetAccessListEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessListEntryExecute provides a mock function with given fields: r
func (_m *ProjectIPAccessListAPI) GetAccessListEntryExecute(r admin.GetAccessListEntryApiRequest) (*admin.NetworkPermissionEntry, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessListEntryExecute")
	}

	var r0 *admin.NetworkPermissionEntry
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetAccessListEntryApiRequest) (*admin.NetworkPermissionEntry, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetAccessListEntryApiRequest) *admin.NetworkPermissionEntry); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.NetworkPermissionEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetAccessListEntryApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetAccessListEntryApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProjectIPAccessListAPI_GetAccessListEntryExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessListEntryExecute'
type ProjectIPAccessListAPI_GetAccessListEntryExecute_Call struct {
	*mock.Call
}

// GetAccessListEntryExecute is a helper method to define mock.On call
//   - r admin.GetAccessListEntryApiRequest
func (_e *ProjectIPAccessListAPI_Expecter) GetAccessListEntryExecute(r any) *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call {
	return &ProjectIPAccessListAPI_GetAccessListEntryExecute_Call{Call: _e.mock.On("GetAccessListEntryExecute", r)}
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call) Run(run func(r admin.GetAccessListEntryApiRequest)) *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetAccessListEntryApiRequest))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call) Return(_a0 *admin.NetworkPermissionEntry, _a1 *http.Response, _a2 error) *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call) RunAndReturn(run func(admin.GetAccessListEntryApiRequest) (*admin.NetworkPermissionEntry, *http.Response, error)) *ProjectIPAccessListAPI_GetAccessListEntryExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessListEntryWithParams provides a mock function with given fields: ctx, args
func (_m *ProjectIPAccessListAPI) GetAccessListEntryWithParams(ctx context.Context, args *admin.GetAccessListEntryApiParams) admin.GetAccessListEntryApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessListEntryWithParams")
	}

	var r0 admin.GetAccessListEntryApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetAccessListEntryApiParams) admin.GetAccessListEntryApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetAccessListEntryApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessListEntryWithParams'
type ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call struct {
	*mock.Call
}

// GetAccessListEntryWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetAccessListEntryApiParams
func (_e *ProjectIPAccessListAPI_Expecter) GetAccessListEntryWithParams(ctx any, args any) *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call {
	return &ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call{Call: _e.mock.On("GetAccessListEntryWithParams", ctx, args)}
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call) Run(run func(ctx context.Context, args *admin.GetAccessListEntryApiParams)) *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetAccessListEntryApiParams))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call) Return(_a0 admin.GetAccessListEntryApiRequest) *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetAccessListEntryApiParams) admin.GetAccessListEntryApiRequest) *ProjectIPAccessListAPI_GetAccessListEntryWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessListStatus provides a mock function with given fields: ctx, groupId, entryValue
func (_m *ProjectIPAccessListAPI) GetAccessListStatus(ctx context.Context, groupId string, entryValue string) admin.GetAccessListStatusApiRequest {
	ret := _m.Called(ctx, groupId, entryValue)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessListStatus")
	}

	var r0 admin.GetAccessListStatusApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetAccessListStatusApiRequest); ok {
		r0 = rf(ctx, groupId, entryValue)
	} else {
		r0 = ret.Get(0).(admin.GetAccessListStatusApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_GetAccessListStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessListStatus'
type ProjectIPAccessListAPI_GetAccessListStatus_Call struct {
	*mock.Call
}

// GetAccessListStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - entryValue string
func (_e *ProjectIPAccessListAPI_Expecter) GetAccessListStatus(ctx any, groupId any, entryValue any) *ProjectIPAccessListAPI_GetAccessListStatus_Call {
	return &ProjectIPAccessListAPI_GetAccessListStatus_Call{Call: _e.mock.On("GetAccessListStatus", ctx, groupId, entryValue)}
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatus_Call) Run(run func(ctx context.Context, groupId string, entryValue string)) *ProjectIPAccessListAPI_GetAccessListStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatus_Call) Return(_a0 admin.GetAccessListStatusApiRequest) *ProjectIPAccessListAPI_GetAccessListStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatus_Call) RunAndReturn(run func(context.Context, string, string) admin.GetAccessListStatusApiRequest) *ProjectIPAccessListAPI_GetAccessListStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessListStatusExecute provides a mock function with given fields: r
func (_m *ProjectIPAccessListAPI) GetAccessListStatusExecute(r admin.GetAccessListStatusApiRequest) (*admin.NetworkPermissionEntryStatus, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessListStatusExecute")
	}

	var r0 *admin.NetworkPermissionEntryStatus
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetAccessListStatusApiRequest) (*admin.NetworkPermissionEntryStatus, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetAccessListStatusApiRequest) *admin.NetworkPermissionEntryStatus); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.NetworkPermissionEntryStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetAccessListStatusApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetAccessListStatusApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProjectIPAccessListAPI_GetAccessListStatusExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessListStatusExecute'
type ProjectIPAccessListAPI_GetAccessListStatusExecute_Call struct {
	*mock.Call
}

// GetAccessListStatusExecute is a helper method to define mock.On call
//   - r admin.GetAccessListStatusApiRequest
func (_e *ProjectIPAccessListAPI_Expecter) GetAccessListStatusExecute(r any) *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call {
	return &ProjectIPAccessListAPI_GetAccessListStatusExecute_Call{Call: _e.mock.On("GetAccessListStatusExecute", r)}
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call) Run(run func(r admin.GetAccessListStatusApiRequest)) *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetAccessListStatusApiRequest))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call) Return(_a0 *admin.NetworkPermissionEntryStatus, _a1 *http.Response, _a2 error) *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call) RunAndReturn(run func(admin.GetAccessListStatusApiRequest) (*admin.NetworkPermissionEntryStatus, *http.Response, error)) *ProjectIPAccessListAPI_GetAccessListStatusExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessListStatusWithParams provides a mock function with given fields: ctx, args
func (_m *ProjectIPAccessListAPI) GetAccessListStatusWithParams(ctx context.Context, args *admin.GetAccessListStatusApiParams) admin.GetAccessListStatusApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessListStatusWithParams")
	}

	var r0 admin.GetAccessListStatusApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetAccessListStatusApiParams) admin.GetAccessListStatusApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetAccessListStatusApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessListStatusWithParams'
type ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call struct {
	*mock.Call
}

// GetAccessListStatusWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetAccessListStatusApiParams
func (_e *ProjectIPAccessListAPI_Expecter) GetAccessListStatusWithParams(ctx any, args any) *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call {
	return &ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call{Call: _e.mock.On("GetAccessListStatusWithParams", ctx, args)}
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call) Run(run func(ctx context.Context, args *admin.GetAccessListStatusApiParams)) *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetAccessListStatusApiParams))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call) Return(_a0 admin.GetAccessListStatusApiRequest) *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetAccessListStatusApiParams) admin.GetAccessListStatusApiRequest) *ProjectIPAccessListAPI_GetAccessListStatusWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessListEntries provides a mock function with given fields: ctx, groupId
func (_m *ProjectIPAccessListAPI) ListAccessListEntries(ctx context.Context, groupId string) admin.ListAccessListEntriesApiRequest {
	ret := _m.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessListEntries")
	}

	var r0 admin.ListAccessListEntriesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.ListAccessListEntriesApiRequest); ok {
		r0 = rf(ctx, groupId)
	} else {
		r0 = ret.Get(0).(admin.ListAccessListEntriesApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_ListAccessListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessListEntries'
type ProjectIPAccessListAPI_ListAccessListEntries_Call struct {
	*mock.Call
}

// ListAccessListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
func (_e *ProjectIPAccessListAPI_Expecter) ListAccessListEntries(ctx any, groupId any) *ProjectIPAccessListAPI_ListAccessListEntries_Call {
	return &ProjectIPAccessListAPI_ListAccessListEntries_Call{Call: _e.mock.On("ListAccessListEntries", ctx, groupId)}
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntries_Call) Run(run func(ctx context.Context, groupId string)) *ProjectIPAccessListAPI_ListAccessListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntries_Call) Return(_a0 admin.ListAccessListEntriesApiRequest) *ProjectIPAccessListAPI_ListAccessListEntries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntries_Call) RunAndReturn(run func(context.Context, string) admin.ListAccessListEntriesApiRequest) *ProjectIPAccessListAPI_ListAccessListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessListEntriesExecute provides a mock function with given fields: r
func (_m *ProjectIPAccessListAPI) ListAccessListEntriesExecute(r admin.ListAccessListEntriesApiRequest) (*admin.PaginatedNetworkAccess, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessListEntriesExecute")
	}

	var r0 *admin.PaginatedNetworkAccess
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListAccessListEntriesApiRequest) (*admin.PaginatedNetworkAccess, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListAccessListEntriesApiRequest) *admin.PaginatedNetworkAccess); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedNetworkAccess)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListAccessListEntriesApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListAccessListEntriesApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessListEntriesExecute'
type ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call struct {
	*mock.Call
}

// ListAccessListEntriesExecute is a helper method to define mock.On call
//   - r admin.ListAccessListEntriesApiRequest
func (_e *ProjectIPAccessListAPI_Expecter) ListAccessListEntriesExecute(r any) *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call {
	return &ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call{Call: _e.mock.On("ListAccessListEntriesExecute", r)}
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call) Run(run func(r admin.ListAccessListEntriesApiRequest)) *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListAccessListEntriesApiRequest))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call) Return(_a0 *admin.PaginatedNetworkAccess, _a1 *http.Response, _a2 error) *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call) RunAndReturn(run func(admin.ListAccessListEntriesApiRequest) (*admin.PaginatedNetworkAccess, *http.Response, error)) *ProjectIPAccessListAPI_ListAccessListEntriesExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessListEntriesWithParams provides a mock function with given fields: ctx, args
func (_m *ProjectIPAccessListAPI) ListAccessListEntriesWithParams(ctx context.Context, args *admin.ListAccessListEntriesApiParams) admin.ListAccessListEntriesApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessListEntriesWithParams")
	}

	var r0 admin.ListAccessListEntriesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListAccessListEntriesApiParams) admin.ListAccessListEntriesApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListAccessListEntriesApiRequest)
	}

	return r0
}

// ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessListEntriesWithParams'
type ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call struct {
	*mock.Call
}

// ListAccessListEntriesWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListAccessListEntriesApiParams
func (_e *ProjectIPAccessListAPI_Expecter) ListAccessListEntriesWithParams(ctx any, args any) *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call {
	return &ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call{Call: _e.mock.On("ListAccessListEntriesWithParams", ctx, args)}
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call) Run(run func(ctx context.Context, args *admin.ListAccessListEntriesApiParams)) *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListAccessListEntriesApiParams))
	})
	return _c
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call) Return(_a0 admin.ListAccessListEntriesApiRequest) *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListAccessListEntriesApiParams) admin.ListAccessListEntriesApiRequest) *ProjectIPAccessListAPI_ListAccessListEntriesWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewProjectIPAccessListAPI creates a new instance of ProjectIPAccessListAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectIPAccessListAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectIPAccessListAPI {
	mock := &ProjectIPAccessListAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
