// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "github.com/mongodb/atlas-sdk-go/admin"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RollingIndexAPI is an autogenerated mock type for the RollingIndexAPI type
type RollingIndexAPI struct {
	mock.Mock
}

type RollingIndexAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *RollingIndexAPI) EXPECT() *RollingIndexAPI_Expecter {
	return &RollingIndexAPI_Expecter{mock: &_m.Mock}
}

// CreateRollingIndex provides a mock function with given fields: ctx, groupId, clusterName, databaseRollingIndexRequest
func (_m *RollingIndexAPI) CreateRollingIndex(ctx context.Context, groupId string, clusterName string, databaseRollingIndexRequest *admin.DatabaseRollingIndexRequest) admin.CreateRollingIndexApiRequest {
	ret := _m.Called(ctx, groupId, clusterName, databaseRollingIndexRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateRollingIndex")
	}

	var r0 admin.CreateRollingIndexApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.DatabaseRollingIndexRequest) admin.CreateRollingIndexApiRequest); ok {
		r0 = rf(ctx, groupId, clusterName, databaseRollingIndexRequest)
	} else {
		r0 = ret.Get(0).(admin.CreateRollingIndexApiRequest)
	}

	return r0
}

// RollingIndexAPI_CreateRollingIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRollingIndex'
type RollingIndexAPI_CreateRollingIndex_Call struct {
	*mock.Call
}

// CreateRollingIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - clusterName string
//   - databaseRollingIndexRequest *admin.DatabaseRollingIndexRequest
func (_e *RollingIndexAPI_Expecter) CreateRollingIndex(ctx any, groupId any, clusterName any, databaseRollingIndexRequest any) *RollingIndexAPI_CreateRollingIndex_Call {
	return &RollingIndexAPI_CreateRollingIndex_Call{Call: _e.mock.On("CreateRollingIndex", ctx, groupId, clusterName, databaseRollingIndexRequest)}
}

func (_c *RollingIndexAPI_CreateRollingIndex_Call) Run(run func(ctx context.Context, groupId string, clusterName string, databaseRollingIndexRequest *admin.DatabaseRollingIndexRequest)) *RollingIndexAPI_CreateRollingIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.DatabaseRollingIndexRequest))
	})
	return _c
}

func (_c *RollingIndexAPI_CreateRollingIndex_Call) Return(_a0 admin.CreateRollingIndexApiRequest) *RollingIndexAPI_CreateRollingIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RollingIndexAPI_CreateRollingIndex_Call) RunAndReturn(run func(context.Context, string, string, *admin.DatabaseRollingIndexRequest) admin.CreateRollingIndexApiRequest) *RollingIndexAPI_CreateRollingIndex_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRollingIndexExecute provides a mock function with given fields: r
func (_m *RollingIndexAPI) CreateRollingIndexExecute(r admin.CreateRollingIndexApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateRollingIndexExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.CreateRollingIndexApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateRollingIndexApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateRollingIndexApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollingIndexAPI_CreateRollingIndexExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRollingIndexExecute'
type RollingIndexAPI_CreateRollingIndexExecute_Call struct {
	*mock.Call
}

// CreateRollingIndexExecute is a helper method to define mock.On call
//   - r admin.CreateRollingIndexApiRequest
func (_e *RollingIndexAPI_Expecter) CreateRollingIndexExecute(r any) *RollingIndexAPI_CreateRollingIndexExecute_Call {
	return &RollingIndexAPI_CreateRollingIndexExecute_Call{Call: _e.mock.On("CreateRollingIndexExecute", r)}
}

func (_c *RollingIndexAPI_CreateRollingIndexExecute_Call) Run(run func(r admin.CreateRollingIndexApiRequest)) *RollingIndexAPI_CreateRollingIndexExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateRollingIndexApiRequest))
	})
	return _c
}

func (_c *RollingIndexAPI_CreateRollingIndexExecute_Call) Return(_a0 *http.Response, _a1 error) *RollingIndexAPI_CreateRollingIndexExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RollingIndexAPI_CreateRollingIndexExecute_Call) RunAndReturn(run func(admin.CreateRollingIndexApiRequest) (*http.Response, error)) *RollingIndexAPI_CreateRollingIndexExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRollingIndexWithParams provides a mock function with given fields: ctx, args
func (_m *RollingIndexAPI) CreateRollingIndexWithParams(ctx context.Context, args *admin.CreateRollingIndexApiParams) admin.CreateRollingIndexApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateRollingIndexWithParams")
	}

	var r0 admin.CreateRollingIndexApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateRollingIndexApiParams) admin.CreateRollingIndexApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateRollingIndexApiRequest)
	}

	return r0
}

// RollingIndexAPI_CreateRollingIndexWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRollingIndexWithParams'
type RollingIndexAPI_CreateRollingIndexWithParams_Call struct {
	*mock.Call
}

// CreateRollingIndexWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateRollingIndexApiParams
func (_e *RollingIndexAPI_Expecter) CreateRollingIndexWithParams(ctx any, args any) *RollingIndexAPI_CreateRollingIndexWithParams_Call {
	return &RollingIndexAPI_CreateRollingIndexWithParams_Call{Call: _e.mock.On("CreateRollingIndexWithParams", ctx, args)}
}

func (_c *RollingIndexAPI_CreateRollingIndexWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateRollingIndexApiParams)) *RollingIndexAPI_CreateRollingIndexWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateRollingIndexApiParams))
	})
	return _c
}

func (_c *RollingIndexAPI_CreateRollingIndexWithParams_Call) Return(_a0 admin.CreateRollingIndexApiRequest) *RollingIndexAPI_CreateRollingIndexWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RollingIndexAPI_CreateRollingIndexWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateRollingIndexApiParams) admin.CreateRollingIndexApiRequest) *RollingIndexAPI_CreateRollingIndexWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewRollingIndexAPI creates a new instance of RollingIndexAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRollingIndexAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *RollingIndexAPI {
	mock := &RollingIndexAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
