// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "go.mongodb.org/atlas-sdk/v20250312023/admin"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RootAPI is an autogenerated mock type for the RootAPI type
type RootAPI struct {
	mock.Mock
}

type RootAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *RootAPI) EXPECT() *RootAPI_Expecter {
	return &RootAPI_Expecter{mock: &_m.Mock}
}

// GetSystemStatus provides a mock function with given fields: ctx
func (_m *RootAPI) GetSystemStatus(ctx context.Context) admin.GetSystemStatusApiRequest {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemStatus")
	}

	var r0 admin.GetSystemStatusApiRequest
	if rf, ok := ret.Get(0).(func(context.Context) admin.GetSystemStatusApiRequest); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(admin.GetSystemStatusApiRequest)
	}

	return r0
}

// RootAPI_GetSystemStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemStatus'
type RootAPI_GetSystemStatus_Call struct {
	*mock.Call
}

// GetSystemStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RootAPI_Expecter) GetSystemStatus(ctx any) *RootAPI_GetSystemStatus_Call {
	return &RootAPI_GetSystemStatus_Call{Call: _e.mock.On("GetSystemStatus", ctx)}
}

func (_c *RootAPI_GetSystemStatus_Call) Run(run func(ctx context.Context)) *RootAPI_GetSystemStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RootAPI_GetSystemStatus_Call) Return(_a0 admin.GetSystemStatusApiRequest) *RootAPI_GetSystemStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RootAPI_GetSystemStatus_Call) RunAndReturn(run func(context.Context) admin.GetSystemStatusApiRequest) *RootAPI_GetSystemStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemStatusExecute provides a mock function with given fields: r
func (_m *RootAPI) GetSystemStatusExecute(r admin.GetSystemStatusApiRequest) (*admin.SystemStatus, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemStatusExecute")
	}

	var r0 *admin.SystemStatus
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetSystemStatusApiRequest) (*admin.SystemStatus, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetSystemStatusApiRequest) *admin.SystemStatus); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.SystemStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetSystemStatusApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetSystemStatusApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RootAPI_GetSystemStatusExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemStatusExecute'
type RootAPI_GetSystemStatusExecute_Call struct {
	*mock.Call
}

// GetSystemStatusExecute is a helper method to define mock.On call
//   - r admin.GetSystemStatusApiRequest
func (_e *RootAPI_Expecter) GetSystemStatusExecute(r any) *RootAPI_GetSystemStatusExecute_Call {
	return &RootAPI_GetSystemStatusExecute_Call{Call: _e.mock.On("GetSystemStatusExecute", r)}
}

func (_c *RootAPI_GetSystemStatusExecute_Call) Run(run func(r admin.GetSystemStatusApiRequest)) *RootAPI_GetSystemStatusExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetSystemStatusApiRequest))
	})
	return _c
}

func (_c *RootAPI_GetSystemStatusExecute_Call) Return(_a0 *admin.SystemStatus, _a1 *http.Response, _a2 error) *RootAPI_GetSystemStatusExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RootAPI_GetSystemStatusExecute_Call) RunAndReturn(run func(admin.GetSystemStatusApiRequest) (*admin.SystemStatus, *http.Response, error)) *RootAPI_GetSystemStatusExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemStatusWithParams provides a mock function with given fields: ctx, args
func (_m *RootAPI) GetSystemStatusWithParams(ctx context.Context, args *admin.GetSystemStatusApiParams) admin.GetSystemStatusApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemStatusWithParams")
	}

	var r0 admin.GetSystemStatusApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetSystemStatusApiParams) admin.GetSystemStatusApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetSystemStatusApiRequest)
	}

	return r0
}

// RootAPI_GetSystemStatusWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemStatusWithParams'
type RootAPI_GetSystemStatusWithParams_Call struct {
	*mock.Call
}

// GetSystemStatusWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetSystemStatusApiParams
func (_e *RootAPI_Expecter) GetSystemStatusWithParams(ctx any, args any) *RootAPI_GetSystemStatusWithParams_Call {
	return &RootAPI_GetSystemStatusWithParams_Call{Call: _e.mock.On("GetSystemStatusWithParams", ctx, args)}
}

func (_c *RootAPI_GetSystemStatusWithParams_Call) Run(run func(ctx context.Context, args *admin.GetSystemStatusApiParams)) *RootAPI_GetSystemStatusWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetSystemStatusApiParams))
	})
	return _c
}

func (_c *RootAPI_GetSystemStatusWithParams_Call) Return(_a0 admin.GetSystemStatusApiRequest) *RootAPI_GetSystemStatusWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RootAPI_GetSystemStatusWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetSystemStatusApiParams) admin.GetSystemStatusApiRequest) *RootAPI_GetSystemStatusWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListControlPlaneAddresses provides a mock function with given fields: ctx
func (_m *RootAPI) ListControlPlaneAddresses(ctx context.Context) admin.ListControlPlaneAddressesApiRequest {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListControlPlaneAddresses")
	}

	var r0 admin.ListControlPlaneAddressesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context) admin.ListControlPlaneAddressesApiRequest); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(admin.ListControlPlaneAddressesApiRequest)
	}

	return r0
}

// RootAPI_ListControlPlaneAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListControlPlaneAddresses'
type RootAPI_ListControlPlaneAddresses_Call struct {
	*mock.Call
}

// ListControlPlaneAddresses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RootAPI_Expecter) ListControlPlaneAddresses(ctx any) *RootAPI_ListControlPlaneAddresses_Call {
	return &RootAPI_ListControlPlaneAddresses_Call{Call: _e.mock.On("ListControlPlaneAddresses", ctx)}
}

func (_c *RootAPI_ListControlPlaneAddresses_Call) Run(run func(ctx context.Context)) *RootAPI_ListControlPlaneAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RootAPI_ListControlPlaneAddresses_Call) Return(_a0 admin.ListControlPlaneAddressesApiRequest) *RootAPI_ListControlPlaneAddresses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RootAPI_ListControlPlaneAddresses_Call) RunAndReturn(run func(context.Context) admin.ListControlPlaneAddressesApiRequest) *RootAPI_ListControlPlaneAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// ListControlPlaneAddressesExecute provides a mock function with given fields: r
func (_m *RootAPI) ListControlPlaneAddressesExecute(r admin.ListControlPlaneAddressesApiRequest) (*admin.ControlPlaneIPAddresses, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListControlPlaneAddressesExecute")
	}

	var r0 *admin.ControlPlaneIPAddresses
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListControlPlaneAddressesApiRequest) (*admin.ControlPlaneIPAddresses, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListControlPlaneAddressesApiRequest) *admin.ControlPlaneIPAddresses); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ControlPlaneIPAddresses)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListControlPlaneAddressesApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListControlPlaneAddressesApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RootAPI_ListControlPlaneAddressesExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListControlPlaneAddressesExecute'
type RootAPI_ListControlPlaneAddressesExecute_Call struct {
	*mock.Call
}

// ListControlPlaneAddressesExecute is a helper method to define mock.On call
//   - r admin.ListControlPlaneAddressesApiRequest
func (_e *RootAPI_Expecter) ListControlPlaneAddressesExecute(r any) *RootAPI_ListControlPlaneAddressesExecute_Call {
	return &RootAPI_ListControlPlaneAddressesExecute_Call{Call: _e.mock.On("ListControlPlaneAddressesExecute", r)}
}

func (_c *RootAPI_ListControlPlaneAddressesExecute_Call) Run(run func(r admin.ListControlPlaneAddressesApiRequest)) *RootAPI_ListControlPlaneAddressesExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListControlPlaneAddressesApiRequest))
	})
	return _c
}

func (_c *RootAPI_ListControlPlaneAddressesExecute_Call) Return(_a0 *admin.ControlPlaneIPAddresses, _a1 *http.Response, _a2 error) *RootAPI_ListControlPlaneAddressesExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RootAPI_ListControlPlaneAddressesExecute_Call) RunAndReturn(run func(admin.ListControlPlaneAddressesApiRequest) (*admin.ControlPlaneIPAddresses, *http.Response, error)) *RootAPI_ListControlPlaneAddressesExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListControlPlaneAddressesWithParams provides a mock function with given fields: ctx, args
func (_m *RootAPI) ListControlPlaneAddressesWithParams(ctx context.Context, args *admin.ListControlPlaneAddressesApiParams) admin.ListControlPlaneAddressesApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListControlPlaneAddressesWithParams")
	}

	var r0 admin.ListControlPlaneAddressesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListControlPlaneAddressesApiParams) admin.ListControlPlaneAddressesApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListControlPlaneAddressesApiRequest)
	}

	return r0
}

// RootAPI_ListControlPlaneAddressesWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListControlPlaneAddressesWithParams'
type RootAPI_ListControlPlaneAddressesWithParams_Call struct {
	*mock.Call
}

// ListControlPlaneAddressesWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListControlPlaneAddressesApiParams
func (_e *RootAPI_Expecter) ListControlPlaneAddressesWithParams(ctx any, args any) *RootAPI_ListControlPlaneAddressesWithParams_Call {
	return &RootAPI_ListControlPlaneAddressesWithParams_Call{Call: _e.mock.On("ListControlPlaneAddressesWithParams", ctx, args)}
}

func (_c *RootAPI_ListControlPlaneAddressesWithParams_Call) Run(run func(ctx context.Context, args *admin.ListControlPlaneAddressesApiParams)) *RootAPI_ListControlPlaneAddressesWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListControlPlaneAddressesApiParams))
	})
	return _c
}

func (_c *RootAPI_ListControlPlaneAddressesWithParams_Call) Return(_a0 admin.ListControlPlaneAddressesApiRequest) *RootAPI_ListControlPlaneAddressesWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RootAPI_ListControlPlaneAddressesWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListControlPlaneAddressesApiParams) admin.ListControlPlaneAddressesApiRequest) *RootAPI_ListControlPlaneAddressesWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewRootAPI creates a new instance of RootAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRootAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *RootAPI {
	mock := &RootAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
