// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "github.com/mongodb/atlas-sdk-go/admin"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// SandboxAPI is an autogenerated mock type for the SandboxAPI type
type SandboxAPI struct {
	mock.Mock
}

type SandboxAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SandboxAPI) EXPECT() *SandboxAPI_Expecter {
	return &SandboxAPI_Expecter{mock: &_m.Mock}
}

// CreateOrgSandboxConfig provides a mock function with given fields: ctx, orgId, sandboxConfigRequest
func (_m *SandboxAPI) CreateOrgSandboxConfig(ctx context.Context, orgId string, sandboxConfigRequest *admin.SandboxConfigRequest) admin.CreateOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, orgId, sandboxConfigRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgSandboxConfig")
	}

	var r0 admin.CreateOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, *admin.SandboxConfigRequest) admin.CreateOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, orgId, sandboxConfigRequest)
	} else {
		r0 = ret.Get(0).(admin.CreateOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_CreateOrgSandboxConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgSandboxConfig'
type SandboxAPI_CreateOrgSandboxConfig_Call struct {
	*mock.Call
}

// CreateOrgSandboxConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - sandboxConfigRequest *admin.SandboxConfigRequest
func (_e *SandboxAPI_Expecter) CreateOrgSandboxConfig(ctx any, orgId any, sandboxConfigRequest any) *SandboxAPI_CreateOrgSandboxConfig_Call {
	return &SandboxAPI_CreateOrgSandboxConfig_Call{Call: _e.mock.On("CreateOrgSandboxConfig", ctx, orgId, sandboxConfigRequest)}
}

func (_c *SandboxAPI_CreateOrgSandboxConfig_Call) Run(run func(ctx context.Context, orgId string, sandboxConfigRequest *admin.SandboxConfigRequest)) *SandboxAPI_CreateOrgSandboxConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*admin.SandboxConfigRequest))
	})
	return _c
}

func (_c *SandboxAPI_CreateOrgSandboxConfig_Call) Return(_a0 admin.CreateOrgSandboxConfigApiRequest) *SandboxAPI_CreateOrgSandboxConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_CreateOrgSandboxConfig_Call) RunAndReturn(run func(context.Context, string, *admin.SandboxConfigRequest) admin.CreateOrgSandboxConfigApiRequest) *SandboxAPI_CreateOrgSandboxConfig_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgSandboxConfigExecute provides a mock function with given fields: r
func (_m *SandboxAPI) CreateOrgSandboxConfigExecute(r admin.CreateOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgSandboxConfigExecute")
	}

	var r0 *admin.SandboxConfigResponse
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateOrgSandboxConfigApiRequest) *admin.SandboxConfigResponse); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.SandboxConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateOrgSandboxConfigApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateOrgSandboxConfigApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SandboxAPI_CreateOrgSandboxConfigExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgSandboxConfigExecute'
type SandboxAPI_CreateOrgSandboxConfigExecute_Call struct {
	*mock.Call
}

// CreateOrgSandboxConfigExecute is a helper method to define mock.On call
//   - r admin.CreateOrgSandboxConfigApiRequest
func (_e *SandboxAPI_Expecter) CreateOrgSandboxConfigExecute(r any) *SandboxAPI_CreateOrgSandboxConfigExecute_Call {
	return &SandboxAPI_CreateOrgSandboxConfigExecute_Call{Call: _e.mock.On("CreateOrgSandboxConfigExecute", r)}
}

func (_c *SandboxAPI_CreateOrgSandboxConfigExecute_Call) Run(run func(r admin.CreateOrgSandboxConfigApiRequest)) *SandboxAPI_CreateOrgSandboxConfigExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateOrgSandboxConfigApiRequest))
	})
	return _c
}

func (_c *SandboxAPI_CreateOrgSandboxConfigExecute_Call) Return(_a0 *admin.SandboxConfigResponse, _a1 *http.Response, _a2 error) *SandboxAPI_CreateOrgSandboxConfigExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SandboxAPI_CreateOrgSandboxConfigExecute_Call) RunAndReturn(run func(admin.CreateOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error)) *SandboxAPI_CreateOrgSandboxConfigExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrgSandboxConfigWithParams provides a mock function with given fields: ctx, args
func (_m *SandboxAPI) CreateOrgSandboxConfigWithParams(ctx context.Context, args *admin.CreateOrgSandboxConfigApiParams) admin.CreateOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrgSandboxConfigWithParams")
	}

	var r0 admin.CreateOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateOrgSandboxConfigApiParams) admin.CreateOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_CreateOrgSandboxConfigWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrgSandboxConfigWithParams'
type SandboxAPI_CreateOrgSandboxConfigWithParams_Call struct {
	*mock.Call
}

// CreateOrgSandboxConfigWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateOrgSandboxConfigApiParams
func (_e *SandboxAPI_Expecter) CreateOrgSandboxConfigWithParams(ctx any, args any) *SandboxAPI_CreateOrgSandboxConfigWithParams_Call {
	return &SandboxAPI_CreateOrgSandboxConfigWithParams_Call{Call: _e.mock.On("CreateOrgSandboxConfigWithParams", ctx, args)}
}

func (_c *SandboxAPI_CreateOrgSandboxConfigWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateOrgSandboxConfigApiParams)) *SandboxAPI_CreateOrgSandboxConfigWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateOrgSandboxConfigApiParams))
	})
	return _c
}

func (_c *SandboxAPI_CreateOrgSandboxConfigWithParams_Call) Return(_a0 admin.CreateOrgSandboxConfigApiRequest) *SandboxAPI_CreateOrgSandboxConfigWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_CreateOrgSandboxConfigWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateOrgSandboxConfigApiParams) admin.CreateOrgSandboxConfigApiRequest) *SandboxAPI_CreateOrgSandboxConfigWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgSandboxConfig provides a mock function with given fields: ctx, orgId, sandboxConfigId
func (_m *SandboxAPI) DeleteOrgSandboxConfig(ctx context.Context, orgId string, sandboxConfigId string) admin.DeleteOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, orgId, sandboxConfigId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgSandboxConfig")
	}

	var r0 admin.DeleteOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.DeleteOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, orgId, sandboxConfigId)
	} else {
		r0 = ret.Get(0).(admin.DeleteOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_DeleteOrgSandboxConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgSandboxConfig'
type SandboxAPI_DeleteOrgSandboxConfig_Call struct {
	*mock.Call
}

// DeleteOrgSandboxConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - sandboxConfigId string
func (_e *SandboxAPI_Expecter) DeleteOrgSandboxConfig(ctx any, orgId any, sandboxConfigId any) *SandboxAPI_DeleteOrgSandboxConfig_Call {
	return &SandboxAPI_DeleteOrgSandboxConfig_Call{Call: _e.mock.On("DeleteOrgSandboxConfig", ctx, orgId, sandboxConfigId)}
}

func (_c *SandboxAPI_DeleteOrgSandboxConfig_Call) Run(run func(ctx context.Context, orgId string, sandboxConfigId string)) *SandboxAPI_DeleteOrgSandboxConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SandboxAPI_DeleteOrgSandboxConfig_Call) Return(_a0 admin.DeleteOrgSandboxConfigApiRequest) *SandboxAPI_DeleteOrgSandboxConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_DeleteOrgSandboxConfig_Call) RunAndReturn(run func(context.Context, string, string) admin.DeleteOrgSandboxConfigApiRequest) *SandboxAPI_DeleteOrgSandboxConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgSandboxConfigExecute provides a mock function with given fields: r
func (_m *SandboxAPI) DeleteOrgSandboxConfigExecute(r admin.DeleteOrgSandboxConfigApiRequest) (*http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgSandboxConfigExecute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(admin.DeleteOrgSandboxConfigApiRequest) (*http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DeleteOrgSandboxConfigApiRequest) *http.Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DeleteOrgSandboxConfigApiRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SandboxAPI_DeleteOrgSandboxConfigExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgSandboxConfigExecute'
type SandboxAPI_DeleteOrgSandboxConfigExecute_Call struct {
	*mock.Call
}

// DeleteOrgSandboxConfigExecute is a helper method to define mock.On call
//   - r admin.DeleteOrgSandboxConfigApiRequest
func (_e *SandboxAPI_Expecter) DeleteOrgSandboxConfigExecute(r any) *SandboxAPI_DeleteOrgSandboxConfigExecute_Call {
	return &SandboxAPI_DeleteOrgSandboxConfigExecute_Call{Call: _e.mock.On("DeleteOrgSandboxConfigExecute", r)}
}

func (_c *SandboxAPI_DeleteOrgSandboxConfigExecute_Call) Run(run func(r admin.DeleteOrgSandboxConfigApiRequest)) *SandboxAPI_DeleteOrgSandboxConfigExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DeleteOrgSandboxConfigApiRequest))
	})
	return _c
}

func (_c *SandboxAPI_DeleteOrgSandboxConfigExecute_Call) Return(_a0 *http.Response, _a1 error) *SandboxAPI_DeleteOrgSandboxConfigExecute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SandboxAPI_DeleteOrgSandboxConfigExecute_Call) RunAndReturn(run func(admin.DeleteOrgSandboxConfigApiRequest) (*http.Response, error)) *SandboxAPI_DeleteOrgSandboxConfigExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrgSandboxConfigWithParams provides a mock function with given fields: ctx, args
func (_m *SandboxAPI) DeleteOrgSandboxConfigWithParams(ctx context.Context, args *admin.DeleteOrgSandboxConfigApiParams) admin.DeleteOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgSandboxConfigWithParams")
	}

	var r0 admin.DeleteOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteOrgSandboxConfigApiParams) admin.DeleteOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DeleteOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_DeleteOrgSandboxConfigWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrgSandboxConfigWithParams'
type SandboxAPI_DeleteOrgSandboxConfigWithParams_Call struct {
	*mock.Call
}

// DeleteOrgSandboxConfigWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DeleteOrgSandboxConfigApiParams
func (_e *SandboxAPI_Expecter) DeleteOrgSandboxConfigWithParams(ctx any, args any) *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call {
	return &SandboxAPI_DeleteOrgSandboxConfigWithParams_Call{Call: _e.mock.On("DeleteOrgSandboxConfigWithParams", ctx, args)}
}

func (_c *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call) Run(run func(ctx context.Context, args *admin.DeleteOrgSandboxConfigApiParams)) *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DeleteOrgSandboxConfigApiParams))
	})
	return _c
}

func (_c *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call) Return(_a0 admin.DeleteOrgSandboxConfigApiRequest) *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call) RunAndReturn(run func(context.Context, *admin.DeleteOrgSandboxConfigApiParams) admin.DeleteOrgSandboxConfigApiRequest) *SandboxAPI_DeleteOrgSandboxConfigWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSandboxClusterDescription provides a mock function with given fields: ctx, groupId, sandboxConfigId
func (_m *SandboxAPI) GenerateSandboxClusterDescription(ctx context.Context, groupId string, sandboxConfigId string) admin.GenerateSandboxClusterDescriptionApiRequest {
	ret := _m.Called(ctx, groupId, sandboxConfigId)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSandboxClusterDescription")
	}

	var r0 admin.GenerateSandboxClusterDescriptionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GenerateSandboxClusterDescriptionApiRequest); ok {
		r0 = rf(ctx, groupId, sandboxConfigId)
	} else {
		r0 = ret.Get(0).(admin.GenerateSandboxClusterDescriptionApiRequest)
	}

	return r0
}

// SandboxAPI_GenerateSandboxClusterDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSandboxClusterDescription'
type SandboxAPI_GenerateSandboxClusterDescription_Call struct {
	*mock.Call
}

// GenerateSandboxClusterDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - sandboxConfigId string
func (_e *SandboxAPI_Expecter) GenerateSandboxClusterDescription(ctx any, groupId any, sandboxConfigId any) *SandboxAPI_GenerateSandboxClusterDescription_Call {
	return &SandboxAPI_GenerateSandboxClusterDescription_Call{Call: _e.mock.On("GenerateSandboxClusterDescription", ctx, groupId, sandboxConfigId)}
}

func (_c *SandboxAPI_GenerateSandboxClusterDescription_Call) Run(run func(ctx context.Context, groupId string, sandboxConfigId string)) *SandboxAPI_GenerateSandboxClusterDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SandboxAPI_GenerateSandboxClusterDescription_Call) Return(_a0 admin.GenerateSandboxClusterDescriptionApiRequest) *SandboxAPI_GenerateSandboxClusterDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_GenerateSandboxClusterDescription_Call) RunAndReturn(run func(context.Context, string, string) admin.GenerateSandboxClusterDescriptionApiRequest) *SandboxAPI_GenerateSandboxClusterDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSandboxClusterDescriptionExecute provides a mock function with given fields: r
func (_m *SandboxAPI) GenerateSandboxClusterDescriptionExecute(r admin.GenerateSandboxClusterDescriptionApiRequest) (*admin.ClusterDescription20240805, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSandboxClusterDescriptionExecute")
	}

	var r0 *admin.ClusterDescription20240805
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GenerateSandboxClusterDescriptionApiRequest) (*admin.ClusterDescription20240805, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GenerateSandboxClusterDescriptionApiRequest) *admin.ClusterDescription20240805); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.ClusterDescription20240805)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GenerateSandboxClusterDescriptionApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GenerateSandboxClusterDescriptionApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSandboxClusterDescriptionExecute'
type SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call struct {
	*mock.Call
}

// GenerateSandboxClusterDescriptionExecute is a helper method to define mock.On call
//   - r admin.GenerateSandboxClusterDescriptionApiRequest
func (_e *SandboxAPI_Expecter) GenerateSandboxClusterDescriptionExecute(r any) *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call {
	return &SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call{Call: _e.mock.On("GenerateSandboxClusterDescriptionExecute", r)}
}

func (_c *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call) Run(run func(r admin.GenerateSandboxClusterDescriptionApiRequest)) *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GenerateSandboxClusterDescriptionApiRequest))
	})
	return _c
}

func (_c *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call) Return(_a0 *admin.ClusterDescription20240805, _a1 *http.Response, _a2 error) *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call) RunAndReturn(run func(admin.GenerateSandboxClusterDescriptionApiRequest) (*admin.ClusterDescription20240805, *http.Response, error)) *SandboxAPI_GenerateSandboxClusterDescriptionExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSandboxClusterDescriptionWithParams provides a mock function with given fields: ctx, args
func (_m *SandboxAPI) GenerateSandboxClusterDescriptionWithParams(ctx context.Context, args *admin.GenerateSandboxClusterDescriptionApiParams) admin.GenerateSandboxClusterDescriptionApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSandboxClusterDescriptionWithParams")
	}

	var r0 admin.GenerateSandboxClusterDescriptionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GenerateSandboxClusterDescriptionApiParams) admin.GenerateSandboxClusterDescriptionApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GenerateSandboxClusterDescriptionApiRequest)
	}

	return r0
}

// SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSandboxClusterDescriptionWithParams'
type SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call struct {
	*mock.Call
}

// GenerateSandboxClusterDescriptionWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GenerateSandboxClusterDescriptionApiParams
func (_e *SandboxAPI_Expecter) GenerateSandboxClusterDescriptionWithParams(ctx any, args any) *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call {
	return &SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call{Call: _e.mock.On("GenerateSandboxClusterDescriptionWithParams", ctx, args)}
}

func (_c *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call) Run(run func(ctx context.Context, args *admin.GenerateSandboxClusterDescriptionApiParams)) *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GenerateSandboxClusterDescriptionApiParams))
	})
	return _c
}

func (_c *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call) Return(_a0 admin.GenerateSandboxClusterDescriptionApiRequest) *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call) RunAndReturn(run func(context.Context, *admin.GenerateSandboxClusterDescriptionApiParams) admin.GenerateSandboxClusterDescriptionApiRequest) *SandboxAPI_GenerateSandboxClusterDescriptionWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgSandboxConfig provides a mock function with given fields: ctx, orgId, sandboxConfigId
func (_m *SandboxAPI) GetOrgSandboxConfig(ctx context.Context, orgId string, sandboxConfigId string) admin.GetOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, orgId, sandboxConfigId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgSandboxConfig")
	}

	var r0 admin.GetOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, orgId, sandboxConfigId)
	} else {
		r0 = ret.Get(0).(admin.GetOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_GetOrgSandboxConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgSandboxConfig'
type SandboxAPI_GetOrgSandboxConfig_Call struct {
	*mock.Call
}

// GetOrgSandboxConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - sandboxConfigId string
func (_e *SandboxAPI_Expecter) GetOrgSandboxConfig(ctx any, orgId any, sandboxConfigId any) *SandboxAPI_GetOrgSandboxConfig_Call {
	return &SandboxAPI_GetOrgSandboxConfig_Call{Call: _e.mock.On("GetOrgSandboxConfig", ctx, orgId, sandboxConfigId)}
}

func (_c *SandboxAPI_GetOrgSandboxConfig_Call) Run(run func(ctx context.Context, orgId string, sandboxConfigId string)) *SandboxAPI_GetOrgSandboxConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SandboxAPI_GetOrgSandboxConfig_Call) Return(_a0 admin.GetOrgSandboxConfigApiRequest) *SandboxAPI_GetOrgSandboxConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_GetOrgSandboxConfig_Call) RunAndReturn(run func(context.Context, string, string) admin.GetOrgSandboxConfigApiRequest) *SandboxAPI_GetOrgSandboxConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgSandboxConfigExecute provides a mock function with given fields: r
func (_m *SandboxAPI) GetOrgSandboxConfigExecute(r admin.GetOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgSandboxConfigExecute")
	}

	var r0 *admin.SandboxConfigResponse
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetOrgSandboxConfigApiRequest) *admin.SandboxConfigResponse); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.SandboxConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetOrgSandboxConfigApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetOrgSandboxConfigApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SandboxAPI_GetOrgSandboxConfigExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgSandboxConfigExecute'
type SandboxAPI_GetOrgSandboxConfigExecute_Call struct {
	*mock.Call
}

// GetOrgSandboxConfigExecute is a helper method to define mock.On call
//   - r admin.GetOrgSandboxConfigApiRequest
func (_e *SandboxAPI_Expecter) GetOrgSandboxConfigExecute(r any) *SandboxAPI_GetOrgSandboxConfigExecute_Call {
	return &SandboxAPI_GetOrgSandboxConfigExecute_Call{Call: _e.mock.On("GetOrgSandboxConfigExecute", r)}
}

func (_c *SandboxAPI_GetOrgSandboxConfigExecute_Call) Run(run func(r admin.GetOrgSandboxConfigApiRequest)) *SandboxAPI_GetOrgSandboxConfigExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetOrgSandboxConfigApiRequest))
	})
	return _c
}

func (_c *SandboxAPI_GetOrgSandboxConfigExecute_Call) Return(_a0 *admin.SandboxConfigResponse, _a1 *http.Response, _a2 error) *SandboxAPI_GetOrgSandboxConfigExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SandboxAPI_GetOrgSandboxConfigExecute_Call) RunAndReturn(run func(admin.GetOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error)) *SandboxAPI_GetOrgSandboxConfigExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgSandboxConfigWithParams provides a mock function with given fields: ctx, args
func (_m *SandboxAPI) GetOrgSandboxConfigWithParams(ctx context.Context, args *admin.GetOrgSandboxConfigApiParams) admin.GetOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgSandboxConfigWithParams")
	}

	var r0 admin.GetOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetOrgSandboxConfigApiParams) admin.GetOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_GetOrgSandboxConfigWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgSandboxConfigWithParams'
type SandboxAPI_GetOrgSandboxConfigWithParams_Call struct {
	*mock.Call
}

// GetOrgSandboxConfigWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetOrgSandboxConfigApiParams
func (_e *SandboxAPI_Expecter) GetOrgSandboxConfigWithParams(ctx any, args any) *SandboxAPI_GetOrgSandboxConfigWithParams_Call {
	return &SandboxAPI_GetOrgSandboxConfigWithParams_Call{Call: _e.mock.On("GetOrgSandboxConfigWithParams", ctx, args)}
}

func (_c *SandboxAPI_GetOrgSandboxConfigWithParams_Call) Run(run func(ctx context.Context, args *admin.GetOrgSandboxConfigApiParams)) *SandboxAPI_GetOrgSandboxConfigWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetOrgSandboxConfigApiParams))
	})
	return _c
}

func (_c *SandboxAPI_GetOrgSandboxConfigWithParams_Call) Return(_a0 admin.GetOrgSandboxConfigApiRequest) *SandboxAPI_GetOrgSandboxConfigWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_GetOrgSandboxConfigWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetOrgSandboxConfigApiParams) admin.GetOrgSandboxConfigApiRequest) *SandboxAPI_GetOrgSandboxConfigWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgSandboxConfig provides a mock function with given fields: ctx, orgId
func (_m *SandboxAPI) ListOrgSandboxConfig(ctx context.Context, orgId string) admin.ListOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, orgId)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgSandboxConfig")
	}

	var r0 admin.ListOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.ListOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, orgId)
	} else {
		r0 = ret.Get(0).(admin.ListOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_ListOrgSandboxConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgSandboxConfig'
type SandboxAPI_ListOrgSandboxConfig_Call struct {
	*mock.Call
}

// ListOrgSandboxConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
func (_e *SandboxAPI_Expecter) ListOrgSandboxConfig(ctx any, orgId any) *SandboxAPI_ListOrgSandboxConfig_Call {
	return &SandboxAPI_ListOrgSandboxConfig_Call{Call: _e.mock.On("ListOrgSandboxConfig", ctx, orgId)}
}

func (_c *SandboxAPI_ListOrgSandboxConfig_Call) Run(run func(ctx context.Context, orgId string)) *SandboxAPI_ListOrgSandboxConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SandboxAPI_ListOrgSandboxConfig_Call) Return(_a0 admin.ListOrgSandboxConfigApiRequest) *SandboxAPI_ListOrgSandboxConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_ListOrgSandboxConfig_Call) RunAndReturn(run func(context.Context, string) admin.ListOrgSandboxConfigApiRequest) *SandboxAPI_ListOrgSandboxConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgSandboxConfigExecute provides a mock function with given fields: r
func (_m *SandboxAPI) ListOrgSandboxConfigExecute(r admin.ListOrgSandboxConfigApiRequest) (*admin.PaginatedSandboxConfigs, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgSandboxConfigExecute")
	}

	var r0 *admin.PaginatedSandboxConfigs
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListOrgSandboxConfigApiRequest) (*admin.PaginatedSandboxConfigs, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListOrgSandboxConfigApiRequest) *admin.PaginatedSandboxConfigs); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedSandboxConfigs)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListOrgSandboxConfigApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListOrgSandboxConfigApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SandboxAPI_ListOrgSandboxConfigExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgSandboxConfigExecute'
type SandboxAPI_ListOrgSandboxConfigExecute_Call struct {
	*mock.Call
}

// ListOrgSandboxConfigExecute is a helper method to define mock.On call
//   - r admin.ListOrgSandboxConfigApiRequest
func (_e *SandboxAPI_Expecter) ListOrgSandboxConfigExecute(r any) *SandboxAPI_ListOrgSandboxConfigExecute_Call {
	return &SandboxAPI_ListOrgSandboxConfigExecute_Call{Call: _e.mock.On("ListOrgSandboxConfigExecute", r)}
}

func (_c *SandboxAPI_ListOrgSandboxConfigExecute_Call) Run(run func(r admin.ListOrgSandboxConfigApiRequest)) *SandboxAPI_ListOrgSandboxConfigExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListOrgSandboxConfigApiRequest))
	})
	return _c
}

func (_c *SandboxAPI_ListOrgSandboxConfigExecute_Call) Return(_a0 *admin.PaginatedSandboxConfigs, _a1 *http.Response, _a2 error) *SandboxAPI_ListOrgSandboxConfigExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SandboxAPI_ListOrgSandboxConfigExecute_Call) RunAndReturn(run func(admin.ListOrgSandboxConfigApiRequest) (*admin.PaginatedSandboxConfigs, *http.Response, error)) *SandboxAPI_ListOrgSandboxConfigExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgSandboxConfigWithParams provides a mock function with given fields: ctx, args
func (_m *SandboxAPI) ListOrgSandboxConfigWithParams(ctx context.Context, args *admin.ListOrgSandboxConfigApiParams) admin.ListOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgSandboxConfigWithParams")
	}

	var r0 admin.ListOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListOrgSandboxConfigApiParams) admin.ListOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_ListOrgSandboxConfigWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgSandboxConfigWithParams'
type SandboxAPI_ListOrgSandboxConfigWithParams_Call struct {
	*mock.Call
}

// ListOrgSandboxConfigWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListOrgSandboxConfigApiParams
func (_e *SandboxAPI_Expecter) ListOrgSandboxConfigWithParams(ctx any, args any) *SandboxAPI_ListOrgSandboxConfigWithParams_Call {
	return &SandboxAPI_ListOrgSandboxConfigWithParams_Call{Call: _e.mock.On("ListOrgSandboxConfigWithParams", ctx, args)}
}

func (_c *SandboxAPI_ListOrgSandboxConfigWithParams_Call) Run(run func(ctx context.Context, args *admin.ListOrgSandboxConfigApiParams)) *SandboxAPI_ListOrgSandboxConfigWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListOrgSandboxConfigApiParams))
	})
	return _c
}

func (_c *SandboxAPI_ListOrgSandboxConfigWithParams_Call) Return(_a0 admin.ListOrgSandboxConfigApiRequest) *SandboxAPI_ListOrgSandboxConfigWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_ListOrgSandboxConfigWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListOrgSandboxConfigApiParams) admin.ListOrgSandboxConfigApiRequest) *SandboxAPI_ListOrgSandboxConfigWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgSandboxConfig provides a mock function with given fields: ctx, orgId, sandboxConfigId, sandboxConfigUpdateRequest
func (_m *SandboxAPI) UpdateOrgSandboxConfig(ctx context.Context, orgId string, sandboxConfigId string, sandboxConfigUpdateRequest *admin.SandboxConfigUpdateRequest) admin.UpdateOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, orgId, sandboxConfigId, sandboxConfigUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgSandboxConfig")
	}

	var r0 admin.UpdateOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.SandboxConfigUpdateRequest) admin.UpdateOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, orgId, sandboxConfigId, sandboxConfigUpdateRequest)
	} else {
		r0 = ret.Get(0).(admin.UpdateOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_UpdateOrgSandboxConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgSandboxConfig'
type SandboxAPI_UpdateOrgSandboxConfig_Call struct {
	*mock.Call
}

// UpdateOrgSandboxConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId string
//   - sandboxConfigId string
//   - sandboxConfigUpdateRequest *admin.SandboxConfigUpdateRequest
func (_e *SandboxAPI_Expecter) UpdateOrgSandboxConfig(ctx any, orgId any, sandboxConfigId any, sandboxConfigUpdateRequest any) *SandboxAPI_UpdateOrgSandboxConfig_Call {
	return &SandboxAPI_UpdateOrgSandboxConfig_Call{Call: _e.mock.On("UpdateOrgSandboxConfig", ctx, orgId, sandboxConfigId, sandboxConfigUpdateRequest)}
}

func (_c *SandboxAPI_UpdateOrgSandboxConfig_Call) Run(run func(ctx context.Context, orgId string, sandboxConfigId string, sandboxConfigUpdateRequest *admin.SandboxConfigUpdateRequest)) *SandboxAPI_UpdateOrgSandboxConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.SandboxConfigUpdateRequest))
	})
	return _c
}

func (_c *SandboxAPI_UpdateOrgSandboxConfig_Call) Return(_a0 admin.UpdateOrgSandboxConfigApiRequest) *SandboxAPI_UpdateOrgSandboxConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_UpdateOrgSandboxConfig_Call) RunAndReturn(run func(context.Context, string, string, *admin.SandboxConfigUpdateRequest) admin.UpdateOrgSandboxConfigApiRequest) *SandboxAPI_UpdateOrgSandboxConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgSandboxConfigExecute provides a mock function with given fields: r
func (_m *SandboxAPI) UpdateOrgSandboxConfigExecute(r admin.UpdateOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgSandboxConfigExecute")
	}

	var r0 *admin.SandboxConfigResponse
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.UpdateOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.UpdateOrgSandboxConfigApiRequest) *admin.SandboxConfigResponse); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.SandboxConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.UpdateOrgSandboxConfigApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.UpdateOrgSandboxConfigApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SandboxAPI_UpdateOrgSandboxConfigExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgSandboxConfigExecute'
type SandboxAPI_UpdateOrgSandboxConfigExecute_Call struct {
	*mock.Call
}

// UpdateOrgSandboxConfigExecute is a helper method to define mock.On call
//   - r admin.UpdateOrgSandboxConfigApiRequest
func (_e *SandboxAPI_Expecter) UpdateOrgSandboxConfigExecute(r any) *SandboxAPI_UpdateOrgSandboxConfigExecute_Call {
	return &SandboxAPI_UpdateOrgSandboxConfigExecute_Call{Call: _e.mock.On("UpdateOrgSandboxConfigExecute", r)}
}

func (_c *SandboxAPI_UpdateOrgSandboxConfigExecute_Call) Run(run func(r admin.UpdateOrgSandboxConfigApiRequest)) *SandboxAPI_UpdateOrgSandboxConfigExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.UpdateOrgSandboxConfigApiRequest))
	})
	return _c
}

func (_c *SandboxAPI_UpdateOrgSandboxConfigExecute_Call) Return(_a0 *admin.SandboxConfigResponse, _a1 *http.Response, _a2 error) *SandboxAPI_UpdateOrgSandboxConfigExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SandboxAPI_UpdateOrgSandboxConfigExecute_Call) RunAndReturn(run func(admin.UpdateOrgSandboxConfigApiRequest) (*admin.SandboxConfigResponse, *http.Response, error)) *SandboxAPI_UpdateOrgSandboxConfigExecute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrgSandboxConfigWithParams provides a mock function with given fields: ctx, args
func (_m *SandboxAPI) UpdateOrgSandboxConfigWithParams(ctx context.Context, args *admin.UpdateOrgSandboxConfigApiParams) admin.UpdateOrgSandboxConfigApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrgSandboxConfigWithParams")
	}

	var r0 admin.UpdateOrgSandboxConfigApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.UpdateOrgSandboxConfigApiParams) admin.UpdateOrgSandboxConfigApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.UpdateOrgSandboxConfigApiRequest)
	}

	return r0
}

// SandboxAPI_UpdateOrgSandboxConfigWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrgSandboxConfigWithParams'
type SandboxAPI_UpdateOrgSandboxConfigWithParams_Call struct {
	*mock.Call
}

// UpdateOrgSandboxConfigWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.UpdateOrgSandboxConfigApiParams
func (_e *SandboxAPI_Expecter) UpdateOrgSandboxConfigWithParams(ctx any, args any) *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call {
	return &SandboxAPI_UpdateOrgSandboxConfigWithParams_Call{Call: _e.mock.On("UpdateOrgSandboxConfigWithParams", ctx, args)}
}

func (_c *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call) Run(run func(ctx context.Context, args *admin.UpdateOrgSandboxConfigApiParams)) *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.UpdateOrgSandboxConfigApiParams))
	})
	return _c
}

func (_c *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call) Return(_a0 admin.UpdateOrgSandboxConfigApiRequest) *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call) RunAndReturn(run func(context.Context, *admin.UpdateOrgSandboxConfigApiParams) admin.UpdateOrgSandboxConfigApiRequest) *SandboxAPI_UpdateOrgSandboxConfigWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewSandboxAPI creates a new instance of SandboxAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSandboxAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SandboxAPI {
	mock := &SandboxAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
