// Code generated by mockery. DO NOT EDIT.

package mockadmin

import (
	context "context"

	admin "go.mongodb.org/atlas-sdk/v20240530001/admin"

	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StreamsApi is an autogenerated mock type for the StreamsApi type
type StreamsApi struct {
	mock.Mock
}

type StreamsApi_Expecter struct {
	mock *mock.Mock
}

func (_m *StreamsApi) EXPECT() *StreamsApi_Expecter {
	return &StreamsApi_Expecter{mock: &_m.Mock}
}

// CreateStreamConnection provides a mock function with given fields: ctx, groupId, tenantName, streamsConnection
func (_m *StreamsApi) CreateStreamConnection(ctx context.Context, groupId string, tenantName string, streamsConnection *admin.StreamsConnection) admin.CreateStreamConnectionApiRequest {
	ret := _m.Called(ctx, groupId, tenantName, streamsConnection)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamConnection")
	}

	var r0 admin.CreateStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.StreamsConnection) admin.CreateStreamConnectionApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName, streamsConnection)
	} else {
		r0 = ret.Get(0).(admin.CreateStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_CreateStreamConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamConnection'
type StreamsApi_CreateStreamConnection_Call struct {
	*mock.Call
}

// CreateStreamConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
//   - streamsConnection *admin.StreamsConnection
func (_e *StreamsApi_Expecter) CreateStreamConnection(ctx interface{}, groupId interface{}, tenantName interface{}, streamsConnection interface{}) *StreamsApi_CreateStreamConnection_Call {
	return &StreamsApi_CreateStreamConnection_Call{Call: _e.mock.On("CreateStreamConnection", ctx, groupId, tenantName, streamsConnection)}
}

func (_c *StreamsApi_CreateStreamConnection_Call) Run(run func(ctx context.Context, groupId string, tenantName string, streamsConnection *admin.StreamsConnection)) *StreamsApi_CreateStreamConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.StreamsConnection))
	})
	return _c
}

func (_c *StreamsApi_CreateStreamConnection_Call) Return(_a0 admin.CreateStreamConnectionApiRequest) *StreamsApi_CreateStreamConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_CreateStreamConnection_Call) RunAndReturn(run func(context.Context, string, string, *admin.StreamsConnection) admin.CreateStreamConnectionApiRequest) *StreamsApi_CreateStreamConnection_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStreamConnectionExecute provides a mock function with given fields: r
func (_m *StreamsApi) CreateStreamConnectionExecute(r admin.CreateStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamConnectionExecute")
	}

	var r0 *admin.StreamsConnection
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateStreamConnectionApiRequest) *admin.StreamsConnection); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.StreamsConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateStreamConnectionApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateStreamConnectionApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_CreateStreamConnectionExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamConnectionExecute'
type StreamsApi_CreateStreamConnectionExecute_Call struct {
	*mock.Call
}

// CreateStreamConnectionExecute is a helper method to define mock.On call
//   - r admin.CreateStreamConnectionApiRequest
func (_e *StreamsApi_Expecter) CreateStreamConnectionExecute(r interface{}) *StreamsApi_CreateStreamConnectionExecute_Call {
	return &StreamsApi_CreateStreamConnectionExecute_Call{Call: _e.mock.On("CreateStreamConnectionExecute", r)}
}

func (_c *StreamsApi_CreateStreamConnectionExecute_Call) Run(run func(r admin.CreateStreamConnectionApiRequest)) *StreamsApi_CreateStreamConnectionExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateStreamConnectionApiRequest))
	})
	return _c
}

func (_c *StreamsApi_CreateStreamConnectionExecute_Call) Return(_a0 *admin.StreamsConnection, _a1 *http.Response, _a2 error) *StreamsApi_CreateStreamConnectionExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_CreateStreamConnectionExecute_Call) RunAndReturn(run func(admin.CreateStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error)) *StreamsApi_CreateStreamConnectionExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStreamConnectionWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) CreateStreamConnectionWithParams(ctx context.Context, args *admin.CreateStreamConnectionApiParams) admin.CreateStreamConnectionApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamConnectionWithParams")
	}

	var r0 admin.CreateStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateStreamConnectionApiParams) admin.CreateStreamConnectionApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_CreateStreamConnectionWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamConnectionWithParams'
type StreamsApi_CreateStreamConnectionWithParams_Call struct {
	*mock.Call
}

// CreateStreamConnectionWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateStreamConnectionApiParams
func (_e *StreamsApi_Expecter) CreateStreamConnectionWithParams(ctx interface{}, args interface{}) *StreamsApi_CreateStreamConnectionWithParams_Call {
	return &StreamsApi_CreateStreamConnectionWithParams_Call{Call: _e.mock.On("CreateStreamConnectionWithParams", ctx, args)}
}

func (_c *StreamsApi_CreateStreamConnectionWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateStreamConnectionApiParams)) *StreamsApi_CreateStreamConnectionWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateStreamConnectionApiParams))
	})
	return _c
}

func (_c *StreamsApi_CreateStreamConnectionWithParams_Call) Return(_a0 admin.CreateStreamConnectionApiRequest) *StreamsApi_CreateStreamConnectionWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_CreateStreamConnectionWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateStreamConnectionApiParams) admin.CreateStreamConnectionApiRequest) *StreamsApi_CreateStreamConnectionWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStreamInstance provides a mock function with given fields: ctx, groupId, streamsTenant
func (_m *StreamsApi) CreateStreamInstance(ctx context.Context, groupId string, streamsTenant *admin.StreamsTenant) admin.CreateStreamInstanceApiRequest {
	ret := _m.Called(ctx, groupId, streamsTenant)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamInstance")
	}

	var r0 admin.CreateStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, *admin.StreamsTenant) admin.CreateStreamInstanceApiRequest); ok {
		r0 = rf(ctx, groupId, streamsTenant)
	} else {
		r0 = ret.Get(0).(admin.CreateStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_CreateStreamInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamInstance'
type StreamsApi_CreateStreamInstance_Call struct {
	*mock.Call
}

// CreateStreamInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - streamsTenant *admin.StreamsTenant
func (_e *StreamsApi_Expecter) CreateStreamInstance(ctx interface{}, groupId interface{}, streamsTenant interface{}) *StreamsApi_CreateStreamInstance_Call {
	return &StreamsApi_CreateStreamInstance_Call{Call: _e.mock.On("CreateStreamInstance", ctx, groupId, streamsTenant)}
}

func (_c *StreamsApi_CreateStreamInstance_Call) Run(run func(ctx context.Context, groupId string, streamsTenant *admin.StreamsTenant)) *StreamsApi_CreateStreamInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*admin.StreamsTenant))
	})
	return _c
}

func (_c *StreamsApi_CreateStreamInstance_Call) Return(_a0 admin.CreateStreamInstanceApiRequest) *StreamsApi_CreateStreamInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_CreateStreamInstance_Call) RunAndReturn(run func(context.Context, string, *admin.StreamsTenant) admin.CreateStreamInstanceApiRequest) *StreamsApi_CreateStreamInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStreamInstanceExecute provides a mock function with given fields: r
func (_m *StreamsApi) CreateStreamInstanceExecute(r admin.CreateStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamInstanceExecute")
	}

	var r0 *admin.StreamsTenant
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.CreateStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.CreateStreamInstanceApiRequest) *admin.StreamsTenant); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.StreamsTenant)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.CreateStreamInstanceApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.CreateStreamInstanceApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_CreateStreamInstanceExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamInstanceExecute'
type StreamsApi_CreateStreamInstanceExecute_Call struct {
	*mock.Call
}

// CreateStreamInstanceExecute is a helper method to define mock.On call
//   - r admin.CreateStreamInstanceApiRequest
func (_e *StreamsApi_Expecter) CreateStreamInstanceExecute(r interface{}) *StreamsApi_CreateStreamInstanceExecute_Call {
	return &StreamsApi_CreateStreamInstanceExecute_Call{Call: _e.mock.On("CreateStreamInstanceExecute", r)}
}

func (_c *StreamsApi_CreateStreamInstanceExecute_Call) Run(run func(r admin.CreateStreamInstanceApiRequest)) *StreamsApi_CreateStreamInstanceExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.CreateStreamInstanceApiRequest))
	})
	return _c
}

func (_c *StreamsApi_CreateStreamInstanceExecute_Call) Return(_a0 *admin.StreamsTenant, _a1 *http.Response, _a2 error) *StreamsApi_CreateStreamInstanceExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_CreateStreamInstanceExecute_Call) RunAndReturn(run func(admin.CreateStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error)) *StreamsApi_CreateStreamInstanceExecute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStreamInstanceWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) CreateStreamInstanceWithParams(ctx context.Context, args *admin.CreateStreamInstanceApiParams) admin.CreateStreamInstanceApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamInstanceWithParams")
	}

	var r0 admin.CreateStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.CreateStreamInstanceApiParams) admin.CreateStreamInstanceApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.CreateStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_CreateStreamInstanceWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamInstanceWithParams'
type StreamsApi_CreateStreamInstanceWithParams_Call struct {
	*mock.Call
}

// CreateStreamInstanceWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.CreateStreamInstanceApiParams
func (_e *StreamsApi_Expecter) CreateStreamInstanceWithParams(ctx interface{}, args interface{}) *StreamsApi_CreateStreamInstanceWithParams_Call {
	return &StreamsApi_CreateStreamInstanceWithParams_Call{Call: _e.mock.On("CreateStreamInstanceWithParams", ctx, args)}
}

func (_c *StreamsApi_CreateStreamInstanceWithParams_Call) Run(run func(ctx context.Context, args *admin.CreateStreamInstanceApiParams)) *StreamsApi_CreateStreamInstanceWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.CreateStreamInstanceApiParams))
	})
	return _c
}

func (_c *StreamsApi_CreateStreamInstanceWithParams_Call) Return(_a0 admin.CreateStreamInstanceApiRequest) *StreamsApi_CreateStreamInstanceWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_CreateStreamInstanceWithParams_Call) RunAndReturn(run func(context.Context, *admin.CreateStreamInstanceApiParams) admin.CreateStreamInstanceApiRequest) *StreamsApi_CreateStreamInstanceWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStreamConnection provides a mock function with given fields: ctx, groupId, tenantName, connectionName
func (_m *StreamsApi) DeleteStreamConnection(ctx context.Context, groupId string, tenantName string, connectionName string) admin.DeleteStreamConnectionApiRequest {
	ret := _m.Called(ctx, groupId, tenantName, connectionName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStreamConnection")
	}

	var r0 admin.DeleteStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) admin.DeleteStreamConnectionApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName, connectionName)
	} else {
		r0 = ret.Get(0).(admin.DeleteStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_DeleteStreamConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStreamConnection'
type StreamsApi_DeleteStreamConnection_Call struct {
	*mock.Call
}

// DeleteStreamConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
//   - connectionName string
func (_e *StreamsApi_Expecter) DeleteStreamConnection(ctx interface{}, groupId interface{}, tenantName interface{}, connectionName interface{}) *StreamsApi_DeleteStreamConnection_Call {
	return &StreamsApi_DeleteStreamConnection_Call{Call: _e.mock.On("DeleteStreamConnection", ctx, groupId, tenantName, connectionName)}
}

func (_c *StreamsApi_DeleteStreamConnection_Call) Run(run func(ctx context.Context, groupId string, tenantName string, connectionName string)) *StreamsApi_DeleteStreamConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *StreamsApi_DeleteStreamConnection_Call) Return(_a0 admin.DeleteStreamConnectionApiRequest) *StreamsApi_DeleteStreamConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_DeleteStreamConnection_Call) RunAndReturn(run func(context.Context, string, string, string) admin.DeleteStreamConnectionApiRequest) *StreamsApi_DeleteStreamConnection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStreamConnectionExecute provides a mock function with given fields: r
func (_m *StreamsApi) DeleteStreamConnectionExecute(r admin.DeleteStreamConnectionApiRequest) (map[string]interface{}, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStreamConnectionExecute")
	}

	var r0 map[string]interface{}
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.DeleteStreamConnectionApiRequest) (map[string]interface{}, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DeleteStreamConnectionApiRequest) map[string]interface{}); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DeleteStreamConnectionApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.DeleteStreamConnectionApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_DeleteStreamConnectionExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStreamConnectionExecute'
type StreamsApi_DeleteStreamConnectionExecute_Call struct {
	*mock.Call
}

// DeleteStreamConnectionExecute is a helper method to define mock.On call
//   - r admin.DeleteStreamConnectionApiRequest
func (_e *StreamsApi_Expecter) DeleteStreamConnectionExecute(r interface{}) *StreamsApi_DeleteStreamConnectionExecute_Call {
	return &StreamsApi_DeleteStreamConnectionExecute_Call{Call: _e.mock.On("DeleteStreamConnectionExecute", r)}
}

func (_c *StreamsApi_DeleteStreamConnectionExecute_Call) Run(run func(r admin.DeleteStreamConnectionApiRequest)) *StreamsApi_DeleteStreamConnectionExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DeleteStreamConnectionApiRequest))
	})
	return _c
}

func (_c *StreamsApi_DeleteStreamConnectionExecute_Call) Return(_a0 map[string]interface{}, _a1 *http.Response, _a2 error) *StreamsApi_DeleteStreamConnectionExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_DeleteStreamConnectionExecute_Call) RunAndReturn(run func(admin.DeleteStreamConnectionApiRequest) (map[string]interface{}, *http.Response, error)) *StreamsApi_DeleteStreamConnectionExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStreamConnectionWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) DeleteStreamConnectionWithParams(ctx context.Context, args *admin.DeleteStreamConnectionApiParams) admin.DeleteStreamConnectionApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStreamConnectionWithParams")
	}

	var r0 admin.DeleteStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteStreamConnectionApiParams) admin.DeleteStreamConnectionApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DeleteStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_DeleteStreamConnectionWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStreamConnectionWithParams'
type StreamsApi_DeleteStreamConnectionWithParams_Call struct {
	*mock.Call
}

// DeleteStreamConnectionWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DeleteStreamConnectionApiParams
func (_e *StreamsApi_Expecter) DeleteStreamConnectionWithParams(ctx interface{}, args interface{}) *StreamsApi_DeleteStreamConnectionWithParams_Call {
	return &StreamsApi_DeleteStreamConnectionWithParams_Call{Call: _e.mock.On("DeleteStreamConnectionWithParams", ctx, args)}
}

func (_c *StreamsApi_DeleteStreamConnectionWithParams_Call) Run(run func(ctx context.Context, args *admin.DeleteStreamConnectionApiParams)) *StreamsApi_DeleteStreamConnectionWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DeleteStreamConnectionApiParams))
	})
	return _c
}

func (_c *StreamsApi_DeleteStreamConnectionWithParams_Call) Return(_a0 admin.DeleteStreamConnectionApiRequest) *StreamsApi_DeleteStreamConnectionWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_DeleteStreamConnectionWithParams_Call) RunAndReturn(run func(context.Context, *admin.DeleteStreamConnectionApiParams) admin.DeleteStreamConnectionApiRequest) *StreamsApi_DeleteStreamConnectionWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStreamInstance provides a mock function with given fields: ctx, groupId, tenantName
func (_m *StreamsApi) DeleteStreamInstance(ctx context.Context, groupId string, tenantName string) admin.DeleteStreamInstanceApiRequest {
	ret := _m.Called(ctx, groupId, tenantName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStreamInstance")
	}

	var r0 admin.DeleteStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.DeleteStreamInstanceApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName)
	} else {
		r0 = ret.Get(0).(admin.DeleteStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_DeleteStreamInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStreamInstance'
type StreamsApi_DeleteStreamInstance_Call struct {
	*mock.Call
}

// DeleteStreamInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
func (_e *StreamsApi_Expecter) DeleteStreamInstance(ctx interface{}, groupId interface{}, tenantName interface{}) *StreamsApi_DeleteStreamInstance_Call {
	return &StreamsApi_DeleteStreamInstance_Call{Call: _e.mock.On("DeleteStreamInstance", ctx, groupId, tenantName)}
}

func (_c *StreamsApi_DeleteStreamInstance_Call) Run(run func(ctx context.Context, groupId string, tenantName string)) *StreamsApi_DeleteStreamInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *StreamsApi_DeleteStreamInstance_Call) Return(_a0 admin.DeleteStreamInstanceApiRequest) *StreamsApi_DeleteStreamInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_DeleteStreamInstance_Call) RunAndReturn(run func(context.Context, string, string) admin.DeleteStreamInstanceApiRequest) *StreamsApi_DeleteStreamInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStreamInstanceExecute provides a mock function with given fields: r
func (_m *StreamsApi) DeleteStreamInstanceExecute(r admin.DeleteStreamInstanceApiRequest) (map[string]interface{}, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStreamInstanceExecute")
	}

	var r0 map[string]interface{}
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.DeleteStreamInstanceApiRequest) (map[string]interface{}, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DeleteStreamInstanceApiRequest) map[string]interface{}); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DeleteStreamInstanceApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.DeleteStreamInstanceApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_DeleteStreamInstanceExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStreamInstanceExecute'
type StreamsApi_DeleteStreamInstanceExecute_Call struct {
	*mock.Call
}

// DeleteStreamInstanceExecute is a helper method to define mock.On call
//   - r admin.DeleteStreamInstanceApiRequest
func (_e *StreamsApi_Expecter) DeleteStreamInstanceExecute(r interface{}) *StreamsApi_DeleteStreamInstanceExecute_Call {
	return &StreamsApi_DeleteStreamInstanceExecute_Call{Call: _e.mock.On("DeleteStreamInstanceExecute", r)}
}

func (_c *StreamsApi_DeleteStreamInstanceExecute_Call) Run(run func(r admin.DeleteStreamInstanceApiRequest)) *StreamsApi_DeleteStreamInstanceExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DeleteStreamInstanceApiRequest))
	})
	return _c
}

func (_c *StreamsApi_DeleteStreamInstanceExecute_Call) Return(_a0 map[string]interface{}, _a1 *http.Response, _a2 error) *StreamsApi_DeleteStreamInstanceExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_DeleteStreamInstanceExecute_Call) RunAndReturn(run func(admin.DeleteStreamInstanceApiRequest) (map[string]interface{}, *http.Response, error)) *StreamsApi_DeleteStreamInstanceExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStreamInstanceWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) DeleteStreamInstanceWithParams(ctx context.Context, args *admin.DeleteStreamInstanceApiParams) admin.DeleteStreamInstanceApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStreamInstanceWithParams")
	}

	var r0 admin.DeleteStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DeleteStreamInstanceApiParams) admin.DeleteStreamInstanceApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DeleteStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_DeleteStreamInstanceWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStreamInstanceWithParams'
type StreamsApi_DeleteStreamInstanceWithParams_Call struct {
	*mock.Call
}

// DeleteStreamInstanceWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DeleteStreamInstanceApiParams
func (_e *StreamsApi_Expecter) DeleteStreamInstanceWithParams(ctx interface{}, args interface{}) *StreamsApi_DeleteStreamInstanceWithParams_Call {
	return &StreamsApi_DeleteStreamInstanceWithParams_Call{Call: _e.mock.On("DeleteStreamInstanceWithParams", ctx, args)}
}

func (_c *StreamsApi_DeleteStreamInstanceWithParams_Call) Run(run func(ctx context.Context, args *admin.DeleteStreamInstanceApiParams)) *StreamsApi_DeleteStreamInstanceWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DeleteStreamInstanceApiParams))
	})
	return _c
}

func (_c *StreamsApi_DeleteStreamInstanceWithParams_Call) Return(_a0 admin.DeleteStreamInstanceApiRequest) *StreamsApi_DeleteStreamInstanceWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_DeleteStreamInstanceWithParams_Call) RunAndReturn(run func(context.Context, *admin.DeleteStreamInstanceApiParams) admin.DeleteStreamInstanceApiRequest) *StreamsApi_DeleteStreamInstanceWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStreamTenantAuditLogs provides a mock function with given fields: ctx, groupId, tenantName
func (_m *StreamsApi) DownloadStreamTenantAuditLogs(ctx context.Context, groupId string, tenantName string) admin.DownloadStreamTenantAuditLogsApiRequest {
	ret := _m.Called(ctx, groupId, tenantName)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStreamTenantAuditLogs")
	}

	var r0 admin.DownloadStreamTenantAuditLogsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.DownloadStreamTenantAuditLogsApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName)
	} else {
		r0 = ret.Get(0).(admin.DownloadStreamTenantAuditLogsApiRequest)
	}

	return r0
}

// StreamsApi_DownloadStreamTenantAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStreamTenantAuditLogs'
type StreamsApi_DownloadStreamTenantAuditLogs_Call struct {
	*mock.Call
}

// DownloadStreamTenantAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
func (_e *StreamsApi_Expecter) DownloadStreamTenantAuditLogs(ctx interface{}, groupId interface{}, tenantName interface{}) *StreamsApi_DownloadStreamTenantAuditLogs_Call {
	return &StreamsApi_DownloadStreamTenantAuditLogs_Call{Call: _e.mock.On("DownloadStreamTenantAuditLogs", ctx, groupId, tenantName)}
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogs_Call) Run(run func(ctx context.Context, groupId string, tenantName string)) *StreamsApi_DownloadStreamTenantAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogs_Call) Return(_a0 admin.DownloadStreamTenantAuditLogsApiRequest) *StreamsApi_DownloadStreamTenantAuditLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogs_Call) RunAndReturn(run func(context.Context, string, string) admin.DownloadStreamTenantAuditLogsApiRequest) *StreamsApi_DownloadStreamTenantAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStreamTenantAuditLogsExecute provides a mock function with given fields: r
func (_m *StreamsApi) DownloadStreamTenantAuditLogsExecute(r admin.DownloadStreamTenantAuditLogsApiRequest) (io.ReadCloser, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStreamTenantAuditLogsExecute")
	}

	var r0 io.ReadCloser
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.DownloadStreamTenantAuditLogsApiRequest) (io.ReadCloser, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.DownloadStreamTenantAuditLogsApiRequest) io.ReadCloser); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.DownloadStreamTenantAuditLogsApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.DownloadStreamTenantAuditLogsApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_DownloadStreamTenantAuditLogsExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStreamTenantAuditLogsExecute'
type StreamsApi_DownloadStreamTenantAuditLogsExecute_Call struct {
	*mock.Call
}

// DownloadStreamTenantAuditLogsExecute is a helper method to define mock.On call
//   - r admin.DownloadStreamTenantAuditLogsApiRequest
func (_e *StreamsApi_Expecter) DownloadStreamTenantAuditLogsExecute(r interface{}) *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call {
	return &StreamsApi_DownloadStreamTenantAuditLogsExecute_Call{Call: _e.mock.On("DownloadStreamTenantAuditLogsExecute", r)}
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call) Run(run func(r admin.DownloadStreamTenantAuditLogsApiRequest)) *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.DownloadStreamTenantAuditLogsApiRequest))
	})
	return _c
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call) Return(_a0 io.ReadCloser, _a1 *http.Response, _a2 error) *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call) RunAndReturn(run func(admin.DownloadStreamTenantAuditLogsApiRequest) (io.ReadCloser, *http.Response, error)) *StreamsApi_DownloadStreamTenantAuditLogsExecute_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStreamTenantAuditLogsWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) DownloadStreamTenantAuditLogsWithParams(ctx context.Context, args *admin.DownloadStreamTenantAuditLogsApiParams) admin.DownloadStreamTenantAuditLogsApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStreamTenantAuditLogsWithParams")
	}

	var r0 admin.DownloadStreamTenantAuditLogsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.DownloadStreamTenantAuditLogsApiParams) admin.DownloadStreamTenantAuditLogsApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.DownloadStreamTenantAuditLogsApiRequest)
	}

	return r0
}

// StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStreamTenantAuditLogsWithParams'
type StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call struct {
	*mock.Call
}

// DownloadStreamTenantAuditLogsWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.DownloadStreamTenantAuditLogsApiParams
func (_e *StreamsApi_Expecter) DownloadStreamTenantAuditLogsWithParams(ctx interface{}, args interface{}) *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call {
	return &StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call{Call: _e.mock.On("DownloadStreamTenantAuditLogsWithParams", ctx, args)}
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call) Run(run func(ctx context.Context, args *admin.DownloadStreamTenantAuditLogsApiParams)) *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.DownloadStreamTenantAuditLogsApiParams))
	})
	return _c
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call) Return(_a0 admin.DownloadStreamTenantAuditLogsApiRequest) *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call) RunAndReturn(run func(context.Context, *admin.DownloadStreamTenantAuditLogsApiParams) admin.DownloadStreamTenantAuditLogsApiRequest) *StreamsApi_DownloadStreamTenantAuditLogsWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamConnection provides a mock function with given fields: ctx, groupId, tenantName, connectionName
func (_m *StreamsApi) GetStreamConnection(ctx context.Context, groupId string, tenantName string, connectionName string) admin.GetStreamConnectionApiRequest {
	ret := _m.Called(ctx, groupId, tenantName, connectionName)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamConnection")
	}

	var r0 admin.GetStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) admin.GetStreamConnectionApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName, connectionName)
	} else {
		r0 = ret.Get(0).(admin.GetStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_GetStreamConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamConnection'
type StreamsApi_GetStreamConnection_Call struct {
	*mock.Call
}

// GetStreamConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
//   - connectionName string
func (_e *StreamsApi_Expecter) GetStreamConnection(ctx interface{}, groupId interface{}, tenantName interface{}, connectionName interface{}) *StreamsApi_GetStreamConnection_Call {
	return &StreamsApi_GetStreamConnection_Call{Call: _e.mock.On("GetStreamConnection", ctx, groupId, tenantName, connectionName)}
}

func (_c *StreamsApi_GetStreamConnection_Call) Run(run func(ctx context.Context, groupId string, tenantName string, connectionName string)) *StreamsApi_GetStreamConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *StreamsApi_GetStreamConnection_Call) Return(_a0 admin.GetStreamConnectionApiRequest) *StreamsApi_GetStreamConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_GetStreamConnection_Call) RunAndReturn(run func(context.Context, string, string, string) admin.GetStreamConnectionApiRequest) *StreamsApi_GetStreamConnection_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamConnectionExecute provides a mock function with given fields: r
func (_m *StreamsApi) GetStreamConnectionExecute(r admin.GetStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamConnectionExecute")
	}

	var r0 *admin.StreamsConnection
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetStreamConnectionApiRequest) *admin.StreamsConnection); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.StreamsConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetStreamConnectionApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetStreamConnectionApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_GetStreamConnectionExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamConnectionExecute'
type StreamsApi_GetStreamConnectionExecute_Call struct {
	*mock.Call
}

// GetStreamConnectionExecute is a helper method to define mock.On call
//   - r admin.GetStreamConnectionApiRequest
func (_e *StreamsApi_Expecter) GetStreamConnectionExecute(r interface{}) *StreamsApi_GetStreamConnectionExecute_Call {
	return &StreamsApi_GetStreamConnectionExecute_Call{Call: _e.mock.On("GetStreamConnectionExecute", r)}
}

func (_c *StreamsApi_GetStreamConnectionExecute_Call) Run(run func(r admin.GetStreamConnectionApiRequest)) *StreamsApi_GetStreamConnectionExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetStreamConnectionApiRequest))
	})
	return _c
}

func (_c *StreamsApi_GetStreamConnectionExecute_Call) Return(_a0 *admin.StreamsConnection, _a1 *http.Response, _a2 error) *StreamsApi_GetStreamConnectionExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_GetStreamConnectionExecute_Call) RunAndReturn(run func(admin.GetStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error)) *StreamsApi_GetStreamConnectionExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamConnectionWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) GetStreamConnectionWithParams(ctx context.Context, args *admin.GetStreamConnectionApiParams) admin.GetStreamConnectionApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamConnectionWithParams")
	}

	var r0 admin.GetStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetStreamConnectionApiParams) admin.GetStreamConnectionApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_GetStreamConnectionWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamConnectionWithParams'
type StreamsApi_GetStreamConnectionWithParams_Call struct {
	*mock.Call
}

// GetStreamConnectionWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetStreamConnectionApiParams
func (_e *StreamsApi_Expecter) GetStreamConnectionWithParams(ctx interface{}, args interface{}) *StreamsApi_GetStreamConnectionWithParams_Call {
	return &StreamsApi_GetStreamConnectionWithParams_Call{Call: _e.mock.On("GetStreamConnectionWithParams", ctx, args)}
}

func (_c *StreamsApi_GetStreamConnectionWithParams_Call) Run(run func(ctx context.Context, args *admin.GetStreamConnectionApiParams)) *StreamsApi_GetStreamConnectionWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetStreamConnectionApiParams))
	})
	return _c
}

func (_c *StreamsApi_GetStreamConnectionWithParams_Call) Return(_a0 admin.GetStreamConnectionApiRequest) *StreamsApi_GetStreamConnectionWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_GetStreamConnectionWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetStreamConnectionApiParams) admin.GetStreamConnectionApiRequest) *StreamsApi_GetStreamConnectionWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamInstance provides a mock function with given fields: ctx, groupId, tenantName
func (_m *StreamsApi) GetStreamInstance(ctx context.Context, groupId string, tenantName string) admin.GetStreamInstanceApiRequest {
	ret := _m.Called(ctx, groupId, tenantName)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamInstance")
	}

	var r0 admin.GetStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.GetStreamInstanceApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName)
	} else {
		r0 = ret.Get(0).(admin.GetStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_GetStreamInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamInstance'
type StreamsApi_GetStreamInstance_Call struct {
	*mock.Call
}

// GetStreamInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
func (_e *StreamsApi_Expecter) GetStreamInstance(ctx interface{}, groupId interface{}, tenantName interface{}) *StreamsApi_GetStreamInstance_Call {
	return &StreamsApi_GetStreamInstance_Call{Call: _e.mock.On("GetStreamInstance", ctx, groupId, tenantName)}
}

func (_c *StreamsApi_GetStreamInstance_Call) Run(run func(ctx context.Context, groupId string, tenantName string)) *StreamsApi_GetStreamInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *StreamsApi_GetStreamInstance_Call) Return(_a0 admin.GetStreamInstanceApiRequest) *StreamsApi_GetStreamInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_GetStreamInstance_Call) RunAndReturn(run func(context.Context, string, string) admin.GetStreamInstanceApiRequest) *StreamsApi_GetStreamInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamInstanceExecute provides a mock function with given fields: r
func (_m *StreamsApi) GetStreamInstanceExecute(r admin.GetStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamInstanceExecute")
	}

	var r0 *admin.StreamsTenant
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.GetStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.GetStreamInstanceApiRequest) *admin.StreamsTenant); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.StreamsTenant)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.GetStreamInstanceApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.GetStreamInstanceApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_GetStreamInstanceExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamInstanceExecute'
type StreamsApi_GetStreamInstanceExecute_Call struct {
	*mock.Call
}

// GetStreamInstanceExecute is a helper method to define mock.On call
//   - r admin.GetStreamInstanceApiRequest
func (_e *StreamsApi_Expecter) GetStreamInstanceExecute(r interface{}) *StreamsApi_GetStreamInstanceExecute_Call {
	return &StreamsApi_GetStreamInstanceExecute_Call{Call: _e.mock.On("GetStreamInstanceExecute", r)}
}

func (_c *StreamsApi_GetStreamInstanceExecute_Call) Run(run func(r admin.GetStreamInstanceApiRequest)) *StreamsApi_GetStreamInstanceExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.GetStreamInstanceApiRequest))
	})
	return _c
}

func (_c *StreamsApi_GetStreamInstanceExecute_Call) Return(_a0 *admin.StreamsTenant, _a1 *http.Response, _a2 error) *StreamsApi_GetStreamInstanceExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_GetStreamInstanceExecute_Call) RunAndReturn(run func(admin.GetStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error)) *StreamsApi_GetStreamInstanceExecute_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamInstanceWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) GetStreamInstanceWithParams(ctx context.Context, args *admin.GetStreamInstanceApiParams) admin.GetStreamInstanceApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamInstanceWithParams")
	}

	var r0 admin.GetStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.GetStreamInstanceApiParams) admin.GetStreamInstanceApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.GetStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_GetStreamInstanceWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamInstanceWithParams'
type StreamsApi_GetStreamInstanceWithParams_Call struct {
	*mock.Call
}

// GetStreamInstanceWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.GetStreamInstanceApiParams
func (_e *StreamsApi_Expecter) GetStreamInstanceWithParams(ctx interface{}, args interface{}) *StreamsApi_GetStreamInstanceWithParams_Call {
	return &StreamsApi_GetStreamInstanceWithParams_Call{Call: _e.mock.On("GetStreamInstanceWithParams", ctx, args)}
}

func (_c *StreamsApi_GetStreamInstanceWithParams_Call) Run(run func(ctx context.Context, args *admin.GetStreamInstanceApiParams)) *StreamsApi_GetStreamInstanceWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.GetStreamInstanceApiParams))
	})
	return _c
}

func (_c *StreamsApi_GetStreamInstanceWithParams_Call) Return(_a0 admin.GetStreamInstanceApiRequest) *StreamsApi_GetStreamInstanceWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_GetStreamInstanceWithParams_Call) RunAndReturn(run func(context.Context, *admin.GetStreamInstanceApiParams) admin.GetStreamInstanceApiRequest) *StreamsApi_GetStreamInstanceWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreamConnections provides a mock function with given fields: ctx, groupId, tenantName
func (_m *StreamsApi) ListStreamConnections(ctx context.Context, groupId string, tenantName string) admin.ListStreamConnectionsApiRequest {
	ret := _m.Called(ctx, groupId, tenantName)

	if len(ret) == 0 {
		panic("no return value specified for ListStreamConnections")
	}

	var r0 admin.ListStreamConnectionsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admin.ListStreamConnectionsApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName)
	} else {
		r0 = ret.Get(0).(admin.ListStreamConnectionsApiRequest)
	}

	return r0
}

// StreamsApi_ListStreamConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreamConnections'
type StreamsApi_ListStreamConnections_Call struct {
	*mock.Call
}

// ListStreamConnections is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
func (_e *StreamsApi_Expecter) ListStreamConnections(ctx interface{}, groupId interface{}, tenantName interface{}) *StreamsApi_ListStreamConnections_Call {
	return &StreamsApi_ListStreamConnections_Call{Call: _e.mock.On("ListStreamConnections", ctx, groupId, tenantName)}
}

func (_c *StreamsApi_ListStreamConnections_Call) Run(run func(ctx context.Context, groupId string, tenantName string)) *StreamsApi_ListStreamConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *StreamsApi_ListStreamConnections_Call) Return(_a0 admin.ListStreamConnectionsApiRequest) *StreamsApi_ListStreamConnections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_ListStreamConnections_Call) RunAndReturn(run func(context.Context, string, string) admin.ListStreamConnectionsApiRequest) *StreamsApi_ListStreamConnections_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreamConnectionsExecute provides a mock function with given fields: r
func (_m *StreamsApi) ListStreamConnectionsExecute(r admin.ListStreamConnectionsApiRequest) (*admin.PaginatedApiStreamsConnection, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListStreamConnectionsExecute")
	}

	var r0 *admin.PaginatedApiStreamsConnection
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListStreamConnectionsApiRequest) (*admin.PaginatedApiStreamsConnection, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListStreamConnectionsApiRequest) *admin.PaginatedApiStreamsConnection); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedApiStreamsConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListStreamConnectionsApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListStreamConnectionsApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_ListStreamConnectionsExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreamConnectionsExecute'
type StreamsApi_ListStreamConnectionsExecute_Call struct {
	*mock.Call
}

// ListStreamConnectionsExecute is a helper method to define mock.On call
//   - r admin.ListStreamConnectionsApiRequest
func (_e *StreamsApi_Expecter) ListStreamConnectionsExecute(r interface{}) *StreamsApi_ListStreamConnectionsExecute_Call {
	return &StreamsApi_ListStreamConnectionsExecute_Call{Call: _e.mock.On("ListStreamConnectionsExecute", r)}
}

func (_c *StreamsApi_ListStreamConnectionsExecute_Call) Run(run func(r admin.ListStreamConnectionsApiRequest)) *StreamsApi_ListStreamConnectionsExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListStreamConnectionsApiRequest))
	})
	return _c
}

func (_c *StreamsApi_ListStreamConnectionsExecute_Call) Return(_a0 *admin.PaginatedApiStreamsConnection, _a1 *http.Response, _a2 error) *StreamsApi_ListStreamConnectionsExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_ListStreamConnectionsExecute_Call) RunAndReturn(run func(admin.ListStreamConnectionsApiRequest) (*admin.PaginatedApiStreamsConnection, *http.Response, error)) *StreamsApi_ListStreamConnectionsExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreamConnectionsWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) ListStreamConnectionsWithParams(ctx context.Context, args *admin.ListStreamConnectionsApiParams) admin.ListStreamConnectionsApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListStreamConnectionsWithParams")
	}

	var r0 admin.ListStreamConnectionsApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListStreamConnectionsApiParams) admin.ListStreamConnectionsApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListStreamConnectionsApiRequest)
	}

	return r0
}

// StreamsApi_ListStreamConnectionsWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreamConnectionsWithParams'
type StreamsApi_ListStreamConnectionsWithParams_Call struct {
	*mock.Call
}

// ListStreamConnectionsWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListStreamConnectionsApiParams
func (_e *StreamsApi_Expecter) ListStreamConnectionsWithParams(ctx interface{}, args interface{}) *StreamsApi_ListStreamConnectionsWithParams_Call {
	return &StreamsApi_ListStreamConnectionsWithParams_Call{Call: _e.mock.On("ListStreamConnectionsWithParams", ctx, args)}
}

func (_c *StreamsApi_ListStreamConnectionsWithParams_Call) Run(run func(ctx context.Context, args *admin.ListStreamConnectionsApiParams)) *StreamsApi_ListStreamConnectionsWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListStreamConnectionsApiParams))
	})
	return _c
}

func (_c *StreamsApi_ListStreamConnectionsWithParams_Call) Return(_a0 admin.ListStreamConnectionsApiRequest) *StreamsApi_ListStreamConnectionsWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_ListStreamConnectionsWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListStreamConnectionsApiParams) admin.ListStreamConnectionsApiRequest) *StreamsApi_ListStreamConnectionsWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreamInstances provides a mock function with given fields: ctx, groupId
func (_m *StreamsApi) ListStreamInstances(ctx context.Context, groupId string) admin.ListStreamInstancesApiRequest {
	ret := _m.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for ListStreamInstances")
	}

	var r0 admin.ListStreamInstancesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string) admin.ListStreamInstancesApiRequest); ok {
		r0 = rf(ctx, groupId)
	} else {
		r0 = ret.Get(0).(admin.ListStreamInstancesApiRequest)
	}

	return r0
}

// StreamsApi_ListStreamInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreamInstances'
type StreamsApi_ListStreamInstances_Call struct {
	*mock.Call
}

// ListStreamInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
func (_e *StreamsApi_Expecter) ListStreamInstances(ctx interface{}, groupId interface{}) *StreamsApi_ListStreamInstances_Call {
	return &StreamsApi_ListStreamInstances_Call{Call: _e.mock.On("ListStreamInstances", ctx, groupId)}
}

func (_c *StreamsApi_ListStreamInstances_Call) Run(run func(ctx context.Context, groupId string)) *StreamsApi_ListStreamInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StreamsApi_ListStreamInstances_Call) Return(_a0 admin.ListStreamInstancesApiRequest) *StreamsApi_ListStreamInstances_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_ListStreamInstances_Call) RunAndReturn(run func(context.Context, string) admin.ListStreamInstancesApiRequest) *StreamsApi_ListStreamInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreamInstancesExecute provides a mock function with given fields: r
func (_m *StreamsApi) ListStreamInstancesExecute(r admin.ListStreamInstancesApiRequest) (*admin.PaginatedApiStreamsTenant, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListStreamInstancesExecute")
	}

	var r0 *admin.PaginatedApiStreamsTenant
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.ListStreamInstancesApiRequest) (*admin.PaginatedApiStreamsTenant, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.ListStreamInstancesApiRequest) *admin.PaginatedApiStreamsTenant); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PaginatedApiStreamsTenant)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.ListStreamInstancesApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.ListStreamInstancesApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_ListStreamInstancesExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreamInstancesExecute'
type StreamsApi_ListStreamInstancesExecute_Call struct {
	*mock.Call
}

// ListStreamInstancesExecute is a helper method to define mock.On call
//   - r admin.ListStreamInstancesApiRequest
func (_e *StreamsApi_Expecter) ListStreamInstancesExecute(r interface{}) *StreamsApi_ListStreamInstancesExecute_Call {
	return &StreamsApi_ListStreamInstancesExecute_Call{Call: _e.mock.On("ListStreamInstancesExecute", r)}
}

func (_c *StreamsApi_ListStreamInstancesExecute_Call) Run(run func(r admin.ListStreamInstancesApiRequest)) *StreamsApi_ListStreamInstancesExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.ListStreamInstancesApiRequest))
	})
	return _c
}

func (_c *StreamsApi_ListStreamInstancesExecute_Call) Return(_a0 *admin.PaginatedApiStreamsTenant, _a1 *http.Response, _a2 error) *StreamsApi_ListStreamInstancesExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_ListStreamInstancesExecute_Call) RunAndReturn(run func(admin.ListStreamInstancesApiRequest) (*admin.PaginatedApiStreamsTenant, *http.Response, error)) *StreamsApi_ListStreamInstancesExecute_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreamInstancesWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) ListStreamInstancesWithParams(ctx context.Context, args *admin.ListStreamInstancesApiParams) admin.ListStreamInstancesApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListStreamInstancesWithParams")
	}

	var r0 admin.ListStreamInstancesApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.ListStreamInstancesApiParams) admin.ListStreamInstancesApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.ListStreamInstancesApiRequest)
	}

	return r0
}

// StreamsApi_ListStreamInstancesWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreamInstancesWithParams'
type StreamsApi_ListStreamInstancesWithParams_Call struct {
	*mock.Call
}

// ListStreamInstancesWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.ListStreamInstancesApiParams
func (_e *StreamsApi_Expecter) ListStreamInstancesWithParams(ctx interface{}, args interface{}) *StreamsApi_ListStreamInstancesWithParams_Call {
	return &StreamsApi_ListStreamInstancesWithParams_Call{Call: _e.mock.On("ListStreamInstancesWithParams", ctx, args)}
}

func (_c *StreamsApi_ListStreamInstancesWithParams_Call) Run(run func(ctx context.Context, args *admin.ListStreamInstancesApiParams)) *StreamsApi_ListStreamInstancesWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.ListStreamInstancesApiParams))
	})
	return _c
}

func (_c *StreamsApi_ListStreamInstancesWithParams_Call) Return(_a0 admin.ListStreamInstancesApiRequest) *StreamsApi_ListStreamInstancesWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_ListStreamInstancesWithParams_Call) RunAndReturn(run func(context.Context, *admin.ListStreamInstancesApiParams) admin.ListStreamInstancesApiRequest) *StreamsApi_ListStreamInstancesWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamConnection provides a mock function with given fields: ctx, groupId, tenantName, connectionName, streamsConnection
func (_m *StreamsApi) UpdateStreamConnection(ctx context.Context, groupId string, tenantName string, connectionName string, streamsConnection *admin.StreamsConnection) admin.UpdateStreamConnectionApiRequest {
	ret := _m.Called(ctx, groupId, tenantName, connectionName, streamsConnection)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamConnection")
	}

	var r0 admin.UpdateStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *admin.StreamsConnection) admin.UpdateStreamConnectionApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName, connectionName, streamsConnection)
	} else {
		r0 = ret.Get(0).(admin.UpdateStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_UpdateStreamConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamConnection'
type StreamsApi_UpdateStreamConnection_Call struct {
	*mock.Call
}

// UpdateStreamConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
//   - connectionName string
//   - streamsConnection *admin.StreamsConnection
func (_e *StreamsApi_Expecter) UpdateStreamConnection(ctx interface{}, groupId interface{}, tenantName interface{}, connectionName interface{}, streamsConnection interface{}) *StreamsApi_UpdateStreamConnection_Call {
	return &StreamsApi_UpdateStreamConnection_Call{Call: _e.mock.On("UpdateStreamConnection", ctx, groupId, tenantName, connectionName, streamsConnection)}
}

func (_c *StreamsApi_UpdateStreamConnection_Call) Run(run func(ctx context.Context, groupId string, tenantName string, connectionName string, streamsConnection *admin.StreamsConnection)) *StreamsApi_UpdateStreamConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*admin.StreamsConnection))
	})
	return _c
}

func (_c *StreamsApi_UpdateStreamConnection_Call) Return(_a0 admin.UpdateStreamConnectionApiRequest) *StreamsApi_UpdateStreamConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_UpdateStreamConnection_Call) RunAndReturn(run func(context.Context, string, string, string, *admin.StreamsConnection) admin.UpdateStreamConnectionApiRequest) *StreamsApi_UpdateStreamConnection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamConnectionExecute provides a mock function with given fields: r
func (_m *StreamsApi) UpdateStreamConnectionExecute(r admin.UpdateStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamConnectionExecute")
	}

	var r0 *admin.StreamsConnection
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.UpdateStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.UpdateStreamConnectionApiRequest) *admin.StreamsConnection); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.StreamsConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.UpdateStreamConnectionApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.UpdateStreamConnectionApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_UpdateStreamConnectionExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamConnectionExecute'
type StreamsApi_UpdateStreamConnectionExecute_Call struct {
	*mock.Call
}

// UpdateStreamConnectionExecute is a helper method to define mock.On call
//   - r admin.UpdateStreamConnectionApiRequest
func (_e *StreamsApi_Expecter) UpdateStreamConnectionExecute(r interface{}) *StreamsApi_UpdateStreamConnectionExecute_Call {
	return &StreamsApi_UpdateStreamConnectionExecute_Call{Call: _e.mock.On("UpdateStreamConnectionExecute", r)}
}

func (_c *StreamsApi_UpdateStreamConnectionExecute_Call) Run(run func(r admin.UpdateStreamConnectionApiRequest)) *StreamsApi_UpdateStreamConnectionExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.UpdateStreamConnectionApiRequest))
	})
	return _c
}

func (_c *StreamsApi_UpdateStreamConnectionExecute_Call) Return(_a0 *admin.StreamsConnection, _a1 *http.Response, _a2 error) *StreamsApi_UpdateStreamConnectionExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_UpdateStreamConnectionExecute_Call) RunAndReturn(run func(admin.UpdateStreamConnectionApiRequest) (*admin.StreamsConnection, *http.Response, error)) *StreamsApi_UpdateStreamConnectionExecute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamConnectionWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) UpdateStreamConnectionWithParams(ctx context.Context, args *admin.UpdateStreamConnectionApiParams) admin.UpdateStreamConnectionApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamConnectionWithParams")
	}

	var r0 admin.UpdateStreamConnectionApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.UpdateStreamConnectionApiParams) admin.UpdateStreamConnectionApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.UpdateStreamConnectionApiRequest)
	}

	return r0
}

// StreamsApi_UpdateStreamConnectionWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamConnectionWithParams'
type StreamsApi_UpdateStreamConnectionWithParams_Call struct {
	*mock.Call
}

// UpdateStreamConnectionWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.UpdateStreamConnectionApiParams
func (_e *StreamsApi_Expecter) UpdateStreamConnectionWithParams(ctx interface{}, args interface{}) *StreamsApi_UpdateStreamConnectionWithParams_Call {
	return &StreamsApi_UpdateStreamConnectionWithParams_Call{Call: _e.mock.On("UpdateStreamConnectionWithParams", ctx, args)}
}

func (_c *StreamsApi_UpdateStreamConnectionWithParams_Call) Run(run func(ctx context.Context, args *admin.UpdateStreamConnectionApiParams)) *StreamsApi_UpdateStreamConnectionWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.UpdateStreamConnectionApiParams))
	})
	return _c
}

func (_c *StreamsApi_UpdateStreamConnectionWithParams_Call) Return(_a0 admin.UpdateStreamConnectionApiRequest) *StreamsApi_UpdateStreamConnectionWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_UpdateStreamConnectionWithParams_Call) RunAndReturn(run func(context.Context, *admin.UpdateStreamConnectionApiParams) admin.UpdateStreamConnectionApiRequest) *StreamsApi_UpdateStreamConnectionWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamInstance provides a mock function with given fields: ctx, groupId, tenantName, streamsDataProcessRegion
func (_m *StreamsApi) UpdateStreamInstance(ctx context.Context, groupId string, tenantName string, streamsDataProcessRegion *admin.StreamsDataProcessRegion) admin.UpdateStreamInstanceApiRequest {
	ret := _m.Called(ctx, groupId, tenantName, streamsDataProcessRegion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamInstance")
	}

	var r0 admin.UpdateStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *admin.StreamsDataProcessRegion) admin.UpdateStreamInstanceApiRequest); ok {
		r0 = rf(ctx, groupId, tenantName, streamsDataProcessRegion)
	} else {
		r0 = ret.Get(0).(admin.UpdateStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_UpdateStreamInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamInstance'
type StreamsApi_UpdateStreamInstance_Call struct {
	*mock.Call
}

// UpdateStreamInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - tenantName string
//   - streamsDataProcessRegion *admin.StreamsDataProcessRegion
func (_e *StreamsApi_Expecter) UpdateStreamInstance(ctx interface{}, groupId interface{}, tenantName interface{}, streamsDataProcessRegion interface{}) *StreamsApi_UpdateStreamInstance_Call {
	return &StreamsApi_UpdateStreamInstance_Call{Call: _e.mock.On("UpdateStreamInstance", ctx, groupId, tenantName, streamsDataProcessRegion)}
}

func (_c *StreamsApi_UpdateStreamInstance_Call) Run(run func(ctx context.Context, groupId string, tenantName string, streamsDataProcessRegion *admin.StreamsDataProcessRegion)) *StreamsApi_UpdateStreamInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*admin.StreamsDataProcessRegion))
	})
	return _c
}

func (_c *StreamsApi_UpdateStreamInstance_Call) Return(_a0 admin.UpdateStreamInstanceApiRequest) *StreamsApi_UpdateStreamInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_UpdateStreamInstance_Call) RunAndReturn(run func(context.Context, string, string, *admin.StreamsDataProcessRegion) admin.UpdateStreamInstanceApiRequest) *StreamsApi_UpdateStreamInstance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamInstanceExecute provides a mock function with given fields: r
func (_m *StreamsApi) UpdateStreamInstanceExecute(r admin.UpdateStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamInstanceExecute")
	}

	var r0 *admin.StreamsTenant
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(admin.UpdateStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(admin.UpdateStreamInstanceApiRequest) *admin.StreamsTenant); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.StreamsTenant)
		}
	}

	if rf, ok := ret.Get(1).(func(admin.UpdateStreamInstanceApiRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(admin.UpdateStreamInstanceApiRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StreamsApi_UpdateStreamInstanceExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamInstanceExecute'
type StreamsApi_UpdateStreamInstanceExecute_Call struct {
	*mock.Call
}

// UpdateStreamInstanceExecute is a helper method to define mock.On call
//   - r admin.UpdateStreamInstanceApiRequest
func (_e *StreamsApi_Expecter) UpdateStreamInstanceExecute(r interface{}) *StreamsApi_UpdateStreamInstanceExecute_Call {
	return &StreamsApi_UpdateStreamInstanceExecute_Call{Call: _e.mock.On("UpdateStreamInstanceExecute", r)}
}

func (_c *StreamsApi_UpdateStreamInstanceExecute_Call) Run(run func(r admin.UpdateStreamInstanceApiRequest)) *StreamsApi_UpdateStreamInstanceExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(admin.UpdateStreamInstanceApiRequest))
	})
	return _c
}

func (_c *StreamsApi_UpdateStreamInstanceExecute_Call) Return(_a0 *admin.StreamsTenant, _a1 *http.Response, _a2 error) *StreamsApi_UpdateStreamInstanceExecute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StreamsApi_UpdateStreamInstanceExecute_Call) RunAndReturn(run func(admin.UpdateStreamInstanceApiRequest) (*admin.StreamsTenant, *http.Response, error)) *StreamsApi_UpdateStreamInstanceExecute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStreamInstanceWithParams provides a mock function with given fields: ctx, args
func (_m *StreamsApi) UpdateStreamInstanceWithParams(ctx context.Context, args *admin.UpdateStreamInstanceApiParams) admin.UpdateStreamInstanceApiRequest {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStreamInstanceWithParams")
	}

	var r0 admin.UpdateStreamInstanceApiRequest
	if rf, ok := ret.Get(0).(func(context.Context, *admin.UpdateStreamInstanceApiParams) admin.UpdateStreamInstanceApiRequest); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(admin.UpdateStreamInstanceApiRequest)
	}

	return r0
}

// StreamsApi_UpdateStreamInstanceWithParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStreamInstanceWithParams'
type StreamsApi_UpdateStreamInstanceWithParams_Call struct {
	*mock.Call
}

// UpdateStreamInstanceWithParams is a helper method to define mock.On call
//   - ctx context.Context
//   - args *admin.UpdateStreamInstanceApiParams
func (_e *StreamsApi_Expecter) UpdateStreamInstanceWithParams(ctx interface{}, args interface{}) *StreamsApi_UpdateStreamInstanceWithParams_Call {
	return &StreamsApi_UpdateStreamInstanceWithParams_Call{Call: _e.mock.On("UpdateStreamInstanceWithParams", ctx, args)}
}

func (_c *StreamsApi_UpdateStreamInstanceWithParams_Call) Run(run func(ctx context.Context, args *admin.UpdateStreamInstanceApiParams)) *StreamsApi_UpdateStreamInstanceWithParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*admin.UpdateStreamInstanceApiParams))
	})
	return _c
}

func (_c *StreamsApi_UpdateStreamInstanceWithParams_Call) Return(_a0 admin.UpdateStreamInstanceApiRequest) *StreamsApi_UpdateStreamInstanceWithParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamsApi_UpdateStreamInstanceWithParams_Call) RunAndReturn(run func(context.Context, *admin.UpdateStreamInstanceApiParams) admin.UpdateStreamInstanceApiRequest) *StreamsApi_UpdateStreamInstanceWithParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewStreamsApi creates a new instance of StreamsApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStreamsApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *StreamsApi {
	mock := &StreamsApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
