name: Autorelease
on:
  workflow_dispatch: {} # workflow can be run manually
  push:
    branches:
      - main
    paths: 
      - "**/*.go"  # Trigger on any Go file changes
  
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      is_version_bump: ${{ steps.check-commit.outputs.is_version_bump }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check if this is a version bump commit
        id: check-commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == "chore: bump minor version to"* ]]; then
            echo "is_version_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_version_bump=false" >> $GITHUB_OUTPUT
          fi
      - name: Check for non-breaking changes
        if: steps.check-commit.outputs.is_version_bump == 'false'
        working-directory: ./tools
        run: |
          ./releaser/scripts/breaking-changes.sh
          ./releaser/scripts/update-minor-version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: check-changes
    if: needs.check-changes.outputs.is_version_bump == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Release env
        working-directory: ./tools
        run: |
          ./releaser/scripts/setghenv.sh
      - name: Create Release 
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          body: ${{ env.RELEASE_NOTES }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
      - name: Trigger Go proxy cache refresh
        run: |
          LATEST_SDK_TAG=$(curl -sSfL https://api.github.com/repos/mongodb/atlas-sdk-go/releases/latest | jq -r '.tag_name')
          LATEST_SDK_RELEASE=$(echo "${LATEST_SDK_TAG}" | cut -d '.' -f 1)
          echo "tag: ${LATEST_SDK_TAG}, release: ${LATEST_SDK_RELEASE}"
          curl -sSfL "https://proxy.golang.org/go.mongodb.org/atlas-sdk/${LATEST_SDK_RELEASE}/@v/${LATEST_SDK_TAG}.info"
