name: Autorelease
on:
  workflow_dispatch: {} # workflow can be run manually
  push:
    branches:
      - main
    paths: 
      - "internal/core/version.go"
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Release env
        working-directory: ./tools
        run: |
          ./releaser/scripts/setghenv.sh
      - name: Create Release 
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          body: ${{ env.RELEASE_NOTES }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
      - name: Trigger Go proxy cache refresh
        run: |
          LATEST_SDK_TAG=$(curl -sSfL https://api.github.com/repos/mongodb/atlas-sdk-go/releases/latest | jq -r '.tag_name')
          LATEST_SDK_RELEASE=$(echo "${LATEST_SDK_TAG}" | cut -d '.' -f 1)
          echo "tag: ${LATEST_SDK_TAG}, release: ${LATEST_SDK_RELEASE}"
          curl -sSfL "https://proxy.golang.org/go.mongodb.org/atlas-sdk/${LATEST_SDK_RELEASE}/@v/${LATEST_SDK_TAG}.info"
