name: Generate Dev SDK 
on:
  workflow_dispatch:
  schedule:
   - cron: '30 8 * * MON'
  push:
    branches:
      - master
      - add-verbose-flags
    paths:
      - "tools/**"
  
jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch changes
        working-directory: ./tools
        run: |
          API_BASE_URL=${{ secrets.MDB_CURRENT_API_PREVIEW_URL }} make fetch_openapi
  
