---
name: shellcheck
on:
  pull_request:
    paths:
      - "**/**.sh"

permissions:
  contents: read

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@5f25a17fbd899b24f4b35e9fd978831f6fe9917e
